#!/usr/bin/env python3
"""Add Law & Education programs; strip PublicPolicy tags; refresh meta."""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(Path(__file__).resolve().parent))
from add_programs_batch import base_program, VERIFIED  # noqa: E402
from add_multidisciplinary_programs import merge_inferred_tags  # noqa: E402

DATA_PATH = ROOT / "data" / "programs.json"

NEW_PROGRAMS = [
    # UK — Law
    base_program(
        "uk-kcl-llm",
        "UK", "United Kingdom", "London",
        "King's College London (KCL)", "伦敦国王学院（KCL）",
        "LLM (Master of Laws)", "法学硕士（LLM）",
        ["Law"],
        "KCL Dickson Poon 法学院 LLM，可选国际商法、知识产权等 pathway。",
        40, "https://www.topuniversities.com/universities/kings-college-london",
        "GBP", 35800,
        "https://www.kcl.ac.uk/study/postgraduate-taught/courses/llm-master-of-laws",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.kcl.ac.uk/study/postgraduate-taught/courses/llm-master-of-laws",
        7.0, 100, "英语要求以 KCL 官网为准。",
        ["https://www.kcl.ac.uk/study/postgraduate-taught/courses/llm-master-of-laws"],
        "通常要求法律本科或相关背景；部分 pathway 接受非法本。",
        "https://www.kcl.ac.uk/study/postgraduate-taught/courses/llm-master-of-laws",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.kcl.ac.uk/study/postgraduate-taught/courses/llm-master-of-laws",
        "Rolling；建议尽早。",
        [{"name": "Rolling", "start": None, "end": None, "note": ""}],
        "https://www.kcl.ac.uk/study/postgraduate-taught/courses/llm-master-of-laws",
        "2026 entry / rolling",
        "https://www.kcl.ac.uk/study/postgraduate-taught/courses/llm-master-of-laws",
        "匹配", "high", True,
    ),
    base_program(
        "uk-ucl-llm",
        "UK", "United Kingdom", "London",
        "University College London (UCL)", "伦敦大学学院（UCL）",
        "LLM (Master of Laws)", "法学硕士（LLM）",
        ["Law"],
        "UCL 法学院 LLM，含国际商法、人权、知识产权等模块。",
        9, "https://www.topuniversities.com/universities/ucl",
        "GBP", 36500,
        "https://www.ucl.ac.uk/laws/study/llm",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.ucl.ac.uk/laws/study/llm",
        7.5, 109, "英语要求以 UCL 法学院为准。",
        ["https://www.ucl.ac.uk/laws/study/llm"],
        "法律本科或同等；部分模块对非法本开放。",
        "https://www.ucl.ac.uk/laws/study/llm",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.ucl.ac.uk/laws/study/llm",
        "分轮次。",
        [{"name": "Round 1", "start": None, "end": "2026-02-28", "note": "参考"}],
        "https://www.ucl.ac.uk/laws/study/llm",
        "2026 entry",
        "https://www.ucl.ac.uk/laws/study/llm",
        "冲刺", "top", True,
    ),
    base_program(
        "uk-lse-llm",
        "UK", "United Kingdom", "London",
        "The London School of Economics and Political Science (LSE)", "伦敦政治经济学院（LSE）",
        "LLM (Master of Laws)", "法学硕士（LLM）",
        ["Law"],
        "LSE 法学院 LLM，偏商法、竞争法、国际法与监管。",
        56, "https://www.topuniversities.com/universities/london-school-economics-political-science-lse",
        "GBP", 28900,
        "https://www.lse.ac.uk/study-at-lse/graduate/llm",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.lse.ac.uk/study-at-lse/graduate/llm",
        7.0, 100, "Standard profile。",
        ["https://www.lse.ac.uk/study-at-lse/graduate/llm"],
        "法律或相关社会科学背景。",
        "https://www.lse.ac.uk/study-at-lse/graduate/llm",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.lse.ac.uk/study-at-lse/graduate/llm",
        "Rolling。",
        [{"name": "Rolling", "start": None, "end": None, "note": ""}],
        "https://www.lse.ac.uk/study-at-lse/graduate/llm",
        "2026 entry / rolling",
        "https://www.lse.ac.uk/study-at-lse/graduate/llm",
        "冲刺", "high", True,
    ),
    base_program(
        "uk-edinburgh-llm",
        "UK", "United Kingdom", "Edinburgh",
        "The University of Edinburgh", "爱丁堡大学",
        "LLM in Law", "法学硕士（LLM）",
        ["Law"],
        "爱丁堡法学院 LLM，含商法、知识产权、国际法等方向。",
        34, "https://www.topuniversities.com/universities/university-edinburgh",
        "GBP", 28000,
        "https://www.ed.ac.uk/studying/postgraduate/degrees/llm-law",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.ed.ac.uk/studying/postgraduate/degrees/llm-law",
        7.0, 100, "英语要求以官网为准。",
        ["https://www.ed.ac.uk/studying/postgraduate/degrees/llm-law"],
        "法律本科或相关学位。",
        "https://www.ed.ac.uk/studying/postgraduate/degrees/llm-law",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.ed.ac.uk/studying/postgraduate/degrees/llm-law",
        "分轮次。",
        [{"name": "Round 3", "start": None, "end": "2026-05-14", "note": ""}],
        "https://www.ed.ac.uk/studying/postgraduate/degrees/llm-law",
        "2026 entry",
        "https://www.ed.ac.uk/studying/postgraduate/degrees/llm-law",
        "匹配", "high", False,
    ),
    base_program(
        "uk-manchester-llm",
        "UK", "United Kingdom", "Manchester",
        "The University of Manchester", "曼彻斯特大学",
        "LLM (Master of Laws)", "法学硕士（LLM）",
        ["Law"],
        "曼大法学院 LLM，国际商法、知识产权、金融法等。",
        35, "https://www.topuniversities.com/universities/university-manchester",
        "GBP", 29500,
        "https://www.manchester.ac.uk/study/masters/courses/list/11590/llm-master-of-laws/",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.manchester.ac.uk/study/masters/courses/list/11590/llm-master-of-laws/",
        7.0, 100, "英语要求以官网为准。",
        ["https://www.manchester.ac.uk/study/masters/courses/list/11590/llm-master-of-laws/"],
        "法律本科或相关背景。",
        "https://www.manchester.ac.uk/study/masters/courses/list/11590/llm-master-of-laws/",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.manchester.ac.uk/study/masters/courses/list/11590/llm-master-of-laws/",
        "Rolling。",
        [{"name": "Rolling", "start": None, "end": None, "note": ""}],
        "https://www.manchester.ac.uk/study/masters/courses/list/11590/llm-master-of-laws/",
        "2026 entry / rolling",
        "https://www.manchester.ac.uk/study/masters/courses/list/11590/llm-master-of-laws/",
        "匹配", "high", False,
    ),
    # UK — Education
    base_program(
        "uk-ucl-ma-education",
        "UK", "United Kingdom", "London",
        "University College London (UCL)", "伦敦大学学院（UCL）",
        "MA in Education", "教育学文学硕士（MA Education）",
        ["Education"],
        "UCL 教育学院 MA Education，课程与教学、教育政策等方向。",
        9, "https://www.topuniversities.com/universities/ucl",
        "GBP", 32100,
        "https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/education-ma",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/education-ma",
        7.0, 96, "英语要求以 UCL IOE 为准。",
        ["https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/education-ma"],
        "本科任意背景；教育相关经历优先。",
        "https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/education-ma",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/education-ma",
        "Rolling。",
        [{"name": "Rolling", "start": None, "end": None, "note": ""}],
        "https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/education-ma",
        "2026 entry / rolling",
        "https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/education-ma",
        "冲刺", "top", True,
    ),
    base_program(
        "uk-oxford-msc-education",
        "UK", "United Kingdom", "Oxford",
        "University of Oxford", "牛津大学",
        "MSc in Education (Child Development and Education)", "教育学理学硕士",
        ["Education"],
        "牛津教育学 MSc，儿童发展与教育方向（示例方向）。",
        3, "https://www.topuniversities.com/universities/university-oxford",
        "GBP", 32520,
        "https://www.ox.ac.uk/admissions/graduate/courses/msc-education-child-development-and-education",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.ox.ac.uk/admissions/graduate/courses/msc-education-child-development-and-education",
        7.5, 110, "英语要求以 Oxford 官网为准。",
        ["https://www.ox.ac.uk/admissions/graduate/courses/msc-education-child-development-and-education"],
        "强学术背景；相关本科或经历。",
        "https://www.ox.ac.uk/admissions/graduate/courses/msc-education-child-development-and-education",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.ox.ac.uk/admissions/graduate/courses/msc-education-child-development-and-education",
        "分轮次；截止以官网为准。",
        [{"name": "Jan deadline", "start": None, "end": "2026-01-08", "note": "参考"}],
        "https://www.ox.ac.uk/admissions/graduate/courses/msc-education-child-development-and-education",
        "2026 entry",
        "https://www.ox.ac.uk/admissions/graduate/courses/msc-education-child-development-and-education",
        "冲刺", "top", True,
    ),
    base_program(
        "uk-cambridge-mphil-education",
        "UK", "United Kingdom", "Cambridge",
        "University of Cambridge", "剑桥大学",
        "MPhil in Education", "教育学哲学硕士（MPhil）",
        ["Education"],
        "剑桥教育学院 MPhil，教育研究与政策。",
        5, "https://www.topuniversities.com/universities/university-cambridge",
        "GBP", 32000,
        "https://www.postgraduate.study.cam.ac.uk/courses/directory/egegmpmph",
        "学费以官网为准。",
        10, "months", "Full-time",
        "https://www.postgraduate.study.cam.ac.uk/courses/directory/egegmpmph",
        7.5, 110, "英语要求以 Cambridge 官网为准。",
        ["https://www.postgraduate.study.cam.ac.uk/courses/directory/egegmpmph"],
        "优秀本科学位；研究计划重要。",
        "https://www.postgraduate.study.cam.ac.uk/courses/directory/egegmpmph",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.postgraduate.study.cam.ac.uk/courses/directory/egegmpmph",
        "分轮次。",
        [{"name": "Round", "start": None, "end": "2026-01-02", "note": "参考"}],
        "https://www.postgraduate.study.cam.ac.uk/courses/directory/egegmpmph",
        "2026 entry",
        "https://www.postgraduate.study.cam.ac.uk/courses/directory/egegmpmph",
        "冲刺", "top", True,
    ),
    base_program(
        "uk-bristol-msc-education",
        "UK", "United Kingdom", "Bristol",
        "University of Bristol", "布里斯托大学",
        "MSc Education", "教育学理学硕士",
        ["Education"],
        "布里斯托教育学 MSc，含政策、心理学与学习科学等。",
        51, "https://www.topuniversities.com/universities/university-bristol",
        "GBP", 28700,
        "https://www.bristol.ac.uk/study/postgraduate/taught/msc-education/",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.bristol.ac.uk/study/postgraduate/taught/msc-education/",
        6.5, 95, "英语要求以官网为准。",
        ["https://www.bristol.ac.uk/study/postgraduate/taught/msc-education/"],
        "2:1 或相关背景。",
        "https://www.bristol.ac.uk/study/postgraduate/taught/msc-education/",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.bristol.ac.uk/study/postgraduate/taught/msc-education/",
        "建议尽早。",
        [{"name": "Rolling", "start": None, "end": "2026-07-31", "note": ""}],
        "https://www.bristol.ac.uk/study/postgraduate/taught/msc-education/",
        "2026 entry",
        "https://www.bristol.ac.uk/study/postgraduate/taught/msc-education/",
        "匹配", "mid", False,
    ),
    base_program(
        "uk-kcl-ma-education",
        "UK", "United Kingdom", "London",
        "King's College London (KCL)", "伦敦国王学院（KCL）",
        "MA Education", "教育学文学硕士",
        ["Education"],
        "KCL 教育学院 MA Education，领导力、语言教育等 pathway。",
        40, "https://www.topuniversities.com/universities/kings-college-london",
        "GBP", 25200,
        "https://www.kcl.ac.uk/study/postgraduate-taught/courses/education-ma",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.kcl.ac.uk/study/postgraduate-taught/courses/education-ma",
        7.0, 100, "英语要求以 KCL 官网为准。",
        ["https://www.kcl.ac.uk/study/postgraduate-taught/courses/education-ma"],
        "本科任意背景。",
        "https://www.kcl.ac.uk/study/postgraduate-taught/courses/education-ma",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.kcl.ac.uk/study/postgraduate-taught/courses/education-ma",
        "Rolling。",
        [{"name": "Rolling", "start": None, "end": None, "note": ""}],
        "https://www.kcl.ac.uk/study/postgraduate-taught/courses/education-ma",
        "2026 entry / rolling",
        "https://www.kcl.ac.uk/study/postgraduate-taught/courses/education-ma",
        "匹配", "high", False,
    ),
    # US — Law
    base_program(
        "us-nyu-llm",
        "US", "United States", "New York",
        "New York University (NYU)", "纽约大学（NYU）",
        "LLM (Master of Laws)", "法学硕士（LLM）",
        ["Law"],
        "NYU 法学院 LLM，国际法、商法、税法等 specialization。",
        43, "https://www.topuniversities.com/universities/new-york-university-nyu",
        "USD", 78000,
        "https://www.law.nyu.edu/llm",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.law.nyu.edu/llm",
        7.0, 100, "英语要求以 NYU Law 为准。",
        ["https://www.law.nyu.edu/llm"],
        "法律本科或同等（部分国家执业资格）。",
        "https://www.law.nyu.edu/llm",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.law.nyu.edu/llm",
        "分轮次。",
        [{"name": "Round 1", "start": None, "end": "2025-12-15", "note": "参考"}],
        "https://www.law.nyu.edu/llm",
        "2026 entry",
        "https://www.law.nyu.edu/llm",
        "冲刺", "top", True,
    ),
    base_program(
        "us-columbia-llm",
        "US", "United States", "New York",
        "Columbia University", "哥伦比亚大学",
        "LLM (Master of Laws)", "法学硕士（LLM）",
        ["Law"],
        "哥大法学院 LLM，公司法、人权、国际法 track。",
        34, "https://www.topuniversities.com/universities/columbia-university",
        "USD", 82000,
        "https://www.law.columbia.edu/admissions/graduate-legal-studies/llm",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.law.columbia.edu/admissions/graduate-legal-studies/llm",
        7.0, 100, "英语要求以 Columbia Law 为准。",
        ["https://www.law.columbia.edu/admissions/graduate-legal-studies/llm"],
        "法律本科或执业律师背景。",
        "https://www.law.columbia.edu/admissions/graduate-legal-studies/llm",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.law.columbia.edu/admissions/graduate-legal-studies/llm",
        "分轮次。",
        [{"name": "Round 1", "start": None, "end": "2025-12-15", "note": "参考"}],
        "https://www.law.columbia.edu/admissions/graduate-legal-studies/llm",
        "2026 entry",
        "https://www.law.columbia.edu/admissions/graduate-legal-studies/llm",
        "冲刺", "top", True,
    ),
    base_program(
        "us-georgetown-llm",
        "US", "United States", "Washington DC",
        "Georgetown University", "乔治城大学",
        "LLM in International Business and Economic Law", "国际商法 LLM",
        ["Law"],
        "乔治城法学院 LLM，国际商法与经济法方向。",
        301, "https://www.topuniversities.com/universities/georgetown-university",
        "USD", 75000,
        "https://www.law.georgetown.edu/admissions-aid/degree-program-admissions/llm/",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.law.georgetown.edu/admissions-aid/degree-program-admissions/llm/",
        7.0, 100, "英语要求以 Georgetown 官网为准。",
        ["https://www.law.georgetown.edu/admissions-aid/degree-program-admissions/llm/"],
        "法律本科或相关背景。",
        "https://www.law.georgetown.edu/admissions-aid/degree-program-admissions/llm/",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.law.georgetown.edu/admissions-aid/degree-program-admissions/llm/",
        "分轮次。",
        [{"name": "Round 1", "start": None, "end": "2026-01-15", "note": "参考"}],
        "https://www.law.georgetown.edu/admissions-aid/degree-program-admissions/llm/",
        "2026 entry",
        "https://www.law.georgetown.edu/admissions-aid/degree-program-admissions/llm/",
        "匹配", "high", False,
    ),
    # US — Education
    base_program(
        "us-harvard-edm",
        "US", "United States", "Cambridge",
        "Harvard University", "哈佛大学",
        "Ed.M. in Education Policy and Analysis", "教育硕士（Ed.M.）",
        ["Education"],
        "哈佛教育学院 Ed.M.，教育政策与分析方向。",
        4, "https://www.topuniversities.com/universities/harvard-university",
        "USD", 58000,
        "https://www.gse.harvard.edu/degrees/masters",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.gse.harvard.edu/degrees/masters",
        7.0, 100, "英语要求以 Harvard GSE 为准。",
        ["https://www.gse.harvard.edu/degrees/masters"],
        "本科任意背景；强文书与经历。",
        "https://www.gse.harvard.edu/degrees/masters",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.gse.harvard.edu/degrees/masters",
        "分轮次。",
        [{"name": "Round 1", "start": None, "end": "2025-12-01", "note": "参考"}],
        "https://www.gse.harvard.edu/degrees/masters",
        "2026 entry",
        "https://www.gse.harvard.edu/degrees/masters",
        "冲刺", "top", True,
    ),
    base_program(
        "us-stanford-ma-education",
        "US", "United States", "Stanford",
        "Stanford University", "斯坦福大学",
        "MA in Education (Policy, Organization and Leadership Studies)", "教育学文学硕士",
        ["Education"],
        "斯坦福 GSE MA，政策、组织与领导力方向。",
        6, "https://www.topuniversities.com/universities/stanford-university",
        "USD", 62000,
        "https://ed.stanford.edu/academics/masters",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://ed.stanford.edu/academics/masters",
        7.0, 100, "英语要求以 Stanford 官网为准。",
        ["https://ed.stanford.edu/academics/masters"],
        "本科任意背景。",
        "https://ed.stanford.edu/academics/masters",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://ed.stanford.edu/academics/masters",
        "分轮次。",
        [{"name": "Round 1", "start": None, "end": "2025-12-01", "note": "参考"}],
        "https://ed.stanford.edu/academics/masters",
        "2026 entry",
        "https://ed.stanford.edu/academics/masters",
        "冲刺", "top", True,
    ),
    base_program(
        "us-columbia-ma-tesol",
        "US", "United States", "New York",
        "Columbia University", "哥伦比亚大学",
        "MA in TESOL (Teaching English to Speakers of Other Languages)", "对外英语教学 MA（TESOL）",
        ["Education"],
        "哥大教育学院 TESOL MA，英语教学与课程设计。",
        34, "https://www.topuniversities.com/universities/columbia-university",
        "USD", 68000,
        "https://www.tc.columbia.edu/academics/ma/",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.tc.columbia.edu/academics/ma/",
        7.0, 100, "英语要求以 Teachers College 为准。",
        ["https://www.tc.columbia.edu/academics/ma/"],
        "本科任意背景；英语/教育相关优先。",
        "https://www.tc.columbia.edu/academics/ma/",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.tc.columbia.edu/academics/ma/",
        "分轮次。",
        [{"name": "Round 1", "start": None, "end": "2026-01-15", "note": "参考"}],
        "https://www.tc.columbia.edu/academics/ma/",
        "2026 entry",
        "https://www.tc.columbia.edu/academics/ma/",
        "冲刺", "top", True,
    ),
    base_program(
        "us-penn-med",
        "US", "United States", "Philadelphia",
        "University of Pennsylvania", "宾夕法尼亚大学",
        "M.S.Ed. in Teaching, Learning, and Leadership", "教学、学习与领导力教育学硕士",
        ["Education"],
        "宾大 GSE M.S.Ed.，教学、学习与领导力。",
        12, "https://www.topuniversities.com/universities/university-pennsylvania",
        "USD", 60000,
        "https://www.gse.upenn.edu/academics/masters",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.gse.upenn.edu/academics/masters",
        7.0, 100, "英语要求以 Penn GSE 为准。",
        ["https://www.gse.upenn.edu/academics/masters"],
        "本科任意背景。",
        "https://www.gse.upenn.edu/academics/masters",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.gse.upenn.edu/academics/masters",
        "分轮次。",
        [{"name": "Round 1", "start": None, "end": "2026-02-01", "note": "参考"}],
        "https://www.gse.upenn.edu/academics/masters",
        "2026 entry",
        "https://www.gse.upenn.edu/academics/masters",
        "冲刺", "top", True,
    ),
    # Hong Kong — Law & Education
    base_program(
        "hk-hku-llm",
        "HongKong", "Hong Kong SAR", "Hong Kong",
        "The University of Hong Kong (HKU)", "香港大学（HKU）",
        "LLM in Common Law", "普通法法学硕士（LLM）",
        ["Law"],
        "港大法学院 LLM，普通法方向，适合大陆法背景转普通法体系。",
        26, "https://www.topuniversities.com/universities/university-hong-kong",
        "HKD", 220000,
        "https://www.law.hku.hk/programmes/postgraduate/llm",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.law.hku.hk/programmes/postgraduate/llm",
        6.5, 80, "英语要求以 HKU 法学院为准。",
        ["https://www.law.hku.hk/programmes/postgraduate/llm"],
        "法律本科或相关背景。",
        "https://www.law.hku.hk/programmes/postgraduate/llm",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.law.hku.hk/programmes/postgraduate/llm",
        "分轮次。",
        [{"name": "Main Round", "start": None, "end": "2026-02-28", "note": "参考"}],
        "https://www.law.hku.hk/programmes/postgraduate/llm",
        "2026 entry",
        "https://www.law.hku.hk/programmes/postgraduate/llm",
        "冲刺", "top", True,
    ),
    base_program(
        "hk-cuhk-llm",
        "HongKong", "Hong Kong SAR", "Hong Kong",
        "The Chinese University of Hong Kong (CUHK)", "香港中文大学（CUHK）",
        "LLM in Common Law", "普通法法学硕士（LLM）",
        ["Law"],
        "中大法学院 LLM，普通法方向。",
        47, "https://www.topuniversities.com/universities/chinese-university-hong-kong-cuhk",
        "HKD", 180000,
        "https://www.law.cuhk.edu.hk/admissions/postgraduate/llm/",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.law.cuhk.edu.hk/admissions/postgraduate/llm/",
        6.5, 79, "英语要求以 CUHK 官网为准。",
        ["https://www.law.cuhk.edu.hk/admissions/postgraduate/llm/"],
        "法律本科或相关学位。",
        "https://www.law.cuhk.edu.hk/admissions/postgraduate/llm/",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.law.cuhk.edu.hk/admissions/postgraduate/llm/",
        "分轮次。",
        [{"name": "Round 1", "start": None, "end": "2026-01-31", "note": "参考"}],
        "https://www.law.cuhk.edu.hk/admissions/postgraduate/llm/",
        "2026 entry",
        "https://www.law.cuhk.edu.hk/admissions/postgraduate/llm/",
        "匹配", "high", False,
    ),
    base_program(
        "hk-hku-med",
        "HongKong", "Hong Kong SAR", "Hong Kong",
        "The University of Hong Kong (HKU)", "香港大学（HKU）",
        "MEd (Master of Education)", "教育学硕士（MEd）",
        ["Education"],
        "港大教育学院 MEd，含中文教育、STEM 教育、教育行政等方向。",
        26, "https://www.topuniversities.com/universities/university-hong-kong",
        "HKD", 198000,
        "https://web.edu.hku.hk/programme/med",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://web.edu.hku.hk/programme/med",
        6.5, 80, "英语要求以 HKU 教育学院为准。",
        ["https://web.edu.hku.hk/programme/med"],
        "本科任意背景；教育相关经历优先。",
        "https://web.edu.hku.hk/programme/med",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://web.edu.hku.hk/programme/med",
        "分轮次。",
        [{"name": "Main Round", "start": None, "end": "2026-02-28", "note": "参考"}],
        "https://web.edu.hku.hk/programme/med",
        "2026 entry",
        "https://web.edu.hku.hk/programme/med",
        "冲刺", "top", True,
    ),
    base_program(
        "hk-cuhk-med",
        "HongKong", "Hong Kong SAR", "Hong Kong",
        "The Chinese University of Hong Kong (CUHK)", "香港中文大学（CUHK）",
        "MA in Education", "教育学文学硕士",
        ["Education"],
        "中大教育学院 MA Education，课程与教学、教育心理学等。",
        47, "https://www.topuniversities.com/universities/chinese-university-hong-kong-cuhk",
        "HKD", 175000,
        "https://www.fed.cuhk.edu.hk/en/programmes/postgraduate-programmes",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.fed.cuhk.edu.hk/en/programmes/postgraduate-programmes",
        6.5, 79, "英语要求以 CUHK 官网为准。",
        ["https://www.fed.cuhk.edu.hk/en/programmes/postgraduate-programmes"],
        "本科任意背景。",
        "https://www.fed.cuhk.edu.hk/en/programmes/postgraduate-programmes",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.fed.cuhk.edu.hk/en/programmes/postgraduate-programmes",
        "分轮次。",
        [{"name": "Round 1", "start": None, "end": "2026-01-31", "note": "参考"}],
        "https://www.fed.cuhk.edu.hk/en/programmes/postgraduate-programmes",
        "2026 entry",
        "https://www.fed.cuhk.edu.hk/en/programmes/postgraduate-programmes",
        "匹配", "high", False,
    ),
    base_program(
        "hk-eduhk-ma-education",
        "HongKong", "Hong Kong SAR", "Hong Kong",
        "The Education University of Hong Kong (EdUHK)", "香港教育大学",
        "MA in Education (various specializations)", "教育学文学硕士",
        ["Education"],
        "教大 MA Education，香港本土师范院校，含中文/英语/数学教育等。",
        530, "https://www.topuniversities.com/universities/education-university-hong-kong",
        "HKD", 145000,
        "https://www.eduhk.hk/acadprog/postgraduate/",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.eduhk.hk/acadprog/postgraduate/",
        6.5, 79, "英语要求以 EdUHK 官网为准。",
        ["https://www.eduhk.hk/acadprog/postgraduate/"],
        "本科任意背景；教育相关优先。",
        "https://www.eduhk.hk/acadprog/postgraduate/",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.eduhk.hk/acadprog/postgraduate/",
        "分轮次。",
        [{"name": "Round 1", "start": None, "end": "2026-02-28", "note": "参考"}],
        "https://www.eduhk.hk/acadprog/postgraduate/",
        "2026 entry",
        "https://www.eduhk.hk/acadprog/postgraduate/",
        "保底", "accessible", False,
    ),
    # Singapore — Law & Education
    base_program(
        "sg-nus-llm",
        "Singapore", "Singapore", "Singapore",
        "National University of Singapore (NUS)", "新加坡国立大学（NUS）",
        "LLM (Master of Laws)", "法学硕士（LLM）",
        ["Law"],
        "NUS 法学院 LLM，亚洲法、国际仲裁、知识产权等。",
        8, "https://www.topuniversities.com/universities/national-university-singapore-nus",
        "SGD", 45000,
        "https://law.nus.edu.sg/education/llm/",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://law.nus.edu.sg/education/llm/",
        7.0, 100, "英语要求以 NUS Law 为准。",
        ["https://law.nus.edu.sg/education/llm/"],
        "法律本科或相关背景。",
        "https://law.nus.edu.sg/education/llm/",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://law.nus.edu.sg/education/llm/",
        "分轮次。",
        [{"name": "Round 1", "start": None, "end": "2026-02-15", "note": "参考"}],
        "https://law.nus.edu.sg/education/llm/",
        "2026 entry",
        "https://law.nus.edu.sg/education/llm/",
        "冲刺", "top", True,
    ),
    base_program(
        "sg-smu-llm",
        "Singapore", "Singapore", "Singapore",
        "Singapore Management University (SMU)", "新加坡管理大学（SMU）",
        "Master of Laws (LLM)", "法学硕士（LLM）",
        ["Law"],
        "SMU 法学院 LLM，商法、争议解决等 track。",
        511, "https://www.topuniversities.com/universities/singapore-management-university",
        "SGD", 48000,
        "https://law.smu.edu.sg/programmes/llm",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://law.smu.edu.sg/programmes/llm",
        6.5, 90, "英语要求以 SMU 官网为准。",
        ["https://law.smu.edu.sg/programmes/llm"],
        "法律本科或相关背景。",
        "https://law.smu.edu.sg/programmes/llm",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://law.smu.edu.sg/programmes/llm",
        "分轮次。",
        [{"name": "Round 1", "start": None, "end": "2026-02-15", "note": "参考"}],
        "https://law.smu.edu.sg/programmes/llm",
        "2026 entry",
        "https://law.smu.edu.sg/programmes/llm",
        "匹配", "mid", False,
    ),
    base_program(
        "sg-nus-med",
        "Singapore", "Singapore", "Singapore",
        "National University of Singapore (NUS)", "新加坡国立大学（NUS）",
        "Master of Education (MEd)", "教育学硕士（MEd）",
        ["Education"],
        "NUS 教育学院 MEd，教学、课程、教育领导力等 specialization。",
        8, "https://www.topuniversities.com/universities/national-university-singapore-nus",
        "SGD", 42000,
        "https://www.nie.edu.sg/higherdegrees/programmes/master-of-education",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.nie.edu.sg/higherdegrees/programmes/master-of-education",
        6.5, 90, "英语要求以 NIE/NUS 官网为准。",
        ["https://www.nie.edu.sg/higherdegrees/programmes/master-of-education"],
        "本科任意背景；教育相关经历优先。",
        "https://www.nie.edu.sg/higherdegrees/programmes/master-of-education",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.nie.edu.sg/higherdegrees/programmes/master-of-education",
        "分轮次。",
        [{"name": "Round 1", "start": None, "end": "2026-02-15", "note": "参考"}],
        "https://www.nie.edu.sg/higherdegrees/programmes/master-of-education",
        "2026 entry",
        "https://www.nie.edu.sg/higherdegrees/programmes/master-of-education",
        "冲刺", "top", True,
    ),
    base_program(
        "sg-ntu-ma-education",
        "Singapore", "Singapore", "Singapore",
        "Nanyang Technological University (NTU)", "南洋理工大学（NTU）",
        "MA in Education", "教育学文学硕士",
        ["Education"],
        "NTU 国立教育学院 NIE MA Education，教学设计与教育研究。",
        12, "https://www.topuniversities.com/universities/nanyang-technological-university-singapore-ntu",
        "SGD", 38000,
        "https://www.ntu.edu.sg/nie/programmes/graduate-programmes/master-of-arts",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.ntu.edu.sg/nie/programmes/graduate-programmes/master-of-arts",
        6.5, 90, "英语要求以 NTU/NIE 官网为准。",
        ["https://www.ntu.edu.sg/nie/programmes/graduate-programmes/master-of-arts"],
        "本科任意背景。",
        "https://www.ntu.edu.sg/nie/programmes/graduate-programmes/master-of-arts",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.ntu.edu.sg/nie/programmes/graduate-programmes/master-of-arts",
        "分轮次。",
        [{"name": "Round 1", "start": None, "end": "2026-01-31", "note": "参考"}],
        "https://www.ntu.edu.sg/nie/programmes/graduate-programmes/master-of-arts",
        "2026 entry",
        "https://www.ntu.edu.sg/nie/programmes/graduate-programmes/master-of-arts",
        "匹配", "high", False,
    ),
    # Extra — UK/US Law & Education
    base_program(
        "uk-durham-llm",
        "UK", "United Kingdom", "Durham",
        "Durham University", "杜伦大学",
        "LLM (Master of Laws)", "法学硕士（LLM）",
        ["Law"],
        "杜伦法学院 LLM，国际法、商法、环境法等 module。",
        89, "https://www.topuniversities.com/universities/durham-university",
        "GBP", 26900,
        "https://www.durham.ac.uk/study/courses/llm/",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.durham.ac.uk/study/courses/llm/",
        7.0, 100, "英语要求以 Durham 官网为准。",
        ["https://www.durham.ac.uk/study/courses/llm/"],
        "法律本科或相关背景。",
        "https://www.durham.ac.uk/study/courses/llm/",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.durham.ac.uk/study/courses/llm/",
        "Rolling。",
        [{"name": "Rolling", "start": None, "end": None, "note": ""}],
        "https://www.durham.ac.uk/study/courses/llm/",
        "2026 entry / rolling",
        "https://www.durham.ac.uk/study/courses/llm/",
        "匹配", "mid", False,
    ),
    base_program(
        "uk-nottingham-ma-education",
        "UK", "United Kingdom", "Nottingham",
        "University of Nottingham", "诺丁汉大学",
        "MA in Education", "教育学文学硕士",
        ["Education"],
        "诺丁汉教育学院 MA Education，领导力、学习与技术等。",
        97, "https://www.topuniversities.com/universities/university-nottingham",
        "GBP", 24300,
        "https://www.nottingham.ac.uk/pgstudy/course/taught/education-ma",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.nottingham.ac.uk/pgstudy/course/taught/education-ma",
        6.5, 90, "英语要求以 Nottingham 官网为准。",
        ["https://www.nottingham.ac.uk/pgstudy/course/taught/education-ma"],
        "2:1 或相关背景。",
        "https://www.nottingham.ac.uk/pgstudy/course/taught/education-ma",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.nottingham.ac.uk/pgstudy/course/taught/education-ma",
        "Rolling。",
        [{"name": "Rolling", "start": None, "end": None, "note": ""}],
        "https://www.nottingham.ac.uk/pgstudy/course/taught/education-ma",
        "2026 entry / rolling",
        "https://www.nottingham.ac.uk/pgstudy/course/taught/education-ma",
        "匹配", "mid", False,
    ),
    base_program(
        "us-usc-llm",
        "US", "United States", "Los Angeles",
        "University of Southern California (USC)", "南加州大学（USC）",
        "LLM (Master of Laws)", "法学硕士（LLM）",
        ["Law"],
        "USC Gould 法学院 LLM，商法、娱乐法、国际法 track。",
        116, "https://www.topuniversities.com/universities/university-southern-california",
        "USD", 72000,
        "https://gould.usc.edu/academics/llm/",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://gould.usc.edu/academics/llm/",
        7.0, 100, "英语要求以 USC Law 为准。",
        ["https://gould.usc.edu/academics/llm/"],
        "法律本科或相关背景。",
        "https://gould.usc.edu/academics/llm/",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://gould.usc.edu/academics/llm/",
        "分轮次。",
        [{"name": "Round 1", "start": None, "end": "2026-02-01", "note": "参考"}],
        "https://gould.usc.edu/academics/llm/",
        "2026 entry",
        "https://gould.usc.edu/academics/llm/",
        "匹配", "high", False,
    ),
    base_program(
        "us-ucla-med",
        "US", "United States", "Los Angeles",
        "University of California, Los Angeles (UCLA)", "加州大学洛杉矶分校（UCLA）",
        "M.Ed. in Educational Leadership", "教育领导力教育学硕士",
        ["Education"],
        "UCLA 教育学院 M.Ed.，教育领导力方向。",
        46, "https://www.topuniversities.com/universities/university-california-los-angeles-ucla",
        "USD", 55000,
        "https://seis.ucla.edu/academic-programs/masters",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://seis.ucla.edu/academic-programs/masters",
        7.0, 100, "英语要求以 UCLA SEIS 为准。",
        ["https://seis.ucla.edu/academic-programs/masters"],
        "本科任意背景。",
        "https://seis.ucla.edu/academic-programs/masters",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://seis.ucla.edu/academic-programs/masters",
        "分轮次。",
        [{"name": "Round 1", "start": None, "end": "2026-12-01", "note": "参考"}],
        "https://seis.ucla.edu/academic-programs/masters",
        "2026 entry",
        "https://seis.ucla.edu/academic-programs/masters",
        "匹配", "high", False,
    ),
    base_program(
        "hk-cityu-llm",
        "HongKong", "Hong Kong SAR", "Hong Kong",
        "City University of Hong Kong", "香港城市大学",
        "Master of Laws (LLM)", "法学硕士（LLM）",
        ["Law"],
        "城大法学院 LLM，国际法、仲裁、中国法等方向。",
        62, "https://www.topuniversities.com/universities/city-university-hong-kong",
        "HKD", 192000,
        "https://www.cityu.edu.hk/slw/Programmes/LLM",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.cityu.edu.hk/slw/Programmes/LLM",
        6.5, 79, "英语要求以 CityU 官网为准。",
        ["https://www.cityu.edu.hk/slw/Programmes/LLM"],
        "法律本科或相关背景。",
        "https://www.cityu.edu.hk/slw/Programmes/LLM",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.cityu.edu.hk/slw/Programmes/LLM",
        "分轮次。",
        [{"name": "Round 1", "start": None, "end": "2026-02-28", "note": "参考"}],
        "https://www.cityu.edu.hk/slw/Programmes/LLM",
        "2026 entry",
        "https://www.cityu.edu.hk/slw/Programmes/LLM",
        "匹配", "mid", False,
    ),
]


def strip_public_policy(program: dict) -> bool:
    tags = program.get("program", {}).get("tags") or []
    if "PublicPolicy" not in tags:
        return False
    program["program"]["tags"] = [t for t in tags if t != "PublicPolicy"]
    return True


def main():
    data = json.loads(DATA_PATH.read_text(encoding="utf-8"))
    existing_ids = {p["id"] for p in data["programs"]}
    added = []
    skipped = []
    for program in NEW_PROGRAMS:
        if program["id"] in existing_ids:
            skipped.append(program["id"])
            continue
        data["programs"].append(program)
        existing_ids.add(program["id"])
        added.append(program["id"])

    stripped = 0
    retagged = 0
    for program in data["programs"]:
        if strip_public_policy(program):
            stripped += 1
        before = list(program.get("program", {}).get("tags") or [])
        merge_inferred_tags(program)
        after = list(program.get("program", {}).get("tags") or [])
        if after != before:
            retagged += 1

    data["meta"]["last_built_at"] = VERIFIED
    data["meta"]["scope_note"] = (
        f"共 {len(data['programs'])} 个项目；覆盖商科、计算机、传媒、数据科学、法律、教育等；"
        "UK/US/HK/SG；官网公开字段 + 经验性评估。"
    )

    DATA_PATH.write_text(
        json.dumps(data, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(f"Added {len(added)} programs (skipped {len(skipped)} duplicates)")
    print(f"Removed PublicPolicy tag from {stripped} programs")
    print(f"Retagged {retagged} programs")
    print(f"Total programs: {len(data['programs'])}")
    if skipped:
        print("Skipped:", skipped)


if __name__ == "__main__":
    main()
