#!/usr/bin/env python3
"""Append new graduate programs to data/programs.json."""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA_PATH = ROOT / "data" / "programs.json"

VERIFIED = "2026-05-19"
DISCLAIMER = "本 Demo 未抓取该项目的官方 Employment Report；如学校/学院公开，可在 Phase 2 补充。"


def base_program(
    pid,
    region,
    country,
    city,
    uni_en,
    uni_zh,
    prog_en,
    prog_zh,
    tags,
    summary_zh,
    qs_rank,
    qs_url,
    currency,
    amount,
    tuition_url,
    tuition_note,
    duration_value,
    duration_unit,
    duration_note,
    duration_url,
    ielts,
    toefl,
    lang_note,
    lang_urls,
    gpa_note,
    gpa_url,
    gre,
    gmat,
    gre_note,
    gre_url,
    deadline_note,
    rounds,
    deadline_url,
    cycle_label,
    program_url,
    difficulty,
    selectivity,
    list_based,
    min_ielts=None,
    min_toefl=None,
    gre_required=None,
    gmat_required=None,
):
    return {
        "id": pid,
        "region": region,
        "country": country,
        "city": city,
        "university": {"name_en": uni_en, "name_zh": uni_zh},
        "program": {
            "name_en": prog_en,
            "name_zh": prog_zh,
            "degree_level": "Master",
            "tags": tags,
            "summary_zh": summary_zh,
        },
        "qs": {
            "year": 2026,
            "rank": qs_rank,
            "source_url": qs_url,
            "last_verified": VERIFIED,
        },
        "tuition": {
            "currency": currency,
            "amount": amount,
            "period": "total",
            "note": tuition_note,
            "cny_estimate": None,
            "source_url": tuition_url,
            "last_verified": VERIFIED,
        },
        "duration": {
            "value": duration_value,
            "unit": duration_unit,
            "note": duration_note,
            "source_url": duration_url,
            "last_verified": VERIFIED,
        },
        "language_requirement": {
            "official_note": lang_note,
            "ielts": {"overall": ielts, "min_each": 6.0 if ielts else None},
            "toefl_ibt": {"overall": toefl},
            "source_urls": lang_urls,
            "last_verified": VERIFIED,
        },
        "gpa": {
            "official_min": None,
            "official_note": gpa_note,
            "source_url": gpa_url,
            "last_verified": VERIFIED,
        },
        "gre_gmat": {
            "gre": gre,
            "gmat": gmat,
            "official_note": gre_note,
            "source_url": gre_url,
            "last_verified": VERIFIED,
        },
        "deadline": {
            "note": deadline_note,
            "rounds": rounds,
            "source_url": deadline_url,
            "last_verified": VERIFIED,
            "source_urls": [deadline_url],
            "cycle_label": cycle_label,
            "is_fallback": False,
            "fallback_note": None,
        },
        "employment": {
            "status": "数据缺失",
            "note": DISCLAIMER,
            "common_directions": "以项目方向常见就业去向为参考，非官方数据。",
            "common_directions_disclaimer": "此为该领域在业内的常见就业方向，非项目层面的官方数据，仅供参考。",
        },
        "third_party": {
            "admission_background": {"status": "数据缺失", "note": "Phase 1 不引入第三方录取背景数据。"}
        },
        "difficulty_label": {"label": difficulty, "note": "仅供参考：基于 QS 排名与地区竞争强度的经验性标签。"},
        "website": {"program_url": program_url},
        "min_gpa": None,
        "min_ielts": min_ielts if min_ielts is not None else ielts,
        "min_toefl": min_toefl if min_toefl is not None else toefl,
        "gre_required": gre_required,
        "gmat_required": gmat_required,
        "min_work_exp_years": None,
        "selectivity_tier": selectivity,
        "is_list_based": list_based,
    }


NEW_PROGRAMS = [
    # UK — MKT / BA / Finance / Management / Economics / MIS
    base_program(
        "uk-kcl-msc-marketing",
        "UK", "United Kingdom", "London",
        "King's College London (KCL)", "伦敦国王学院（KCL）",
        "MSc Marketing", "市场营销硕士（MSc Marketing）",
        ["MKT"],
        "KCL 商学院市场营销硕士，强调品牌、消费者行为与数字营销。",
        40, "https://www.topuniversities.com/universities/kings-college-london",
        "GBP", 35800,
        "https://www.kcl.ac.uk/study/postgraduate-taught/courses/marketing-msc",
        "2026/27 学年学费以官网为准。",
        12, "months", "Full-time 12 months",
        "https://www.kcl.ac.uk/study/postgraduate-taught/courses/marketing-msc",
        7.0, 100, "官方英语要求以 KCL 研究生英语要求页为准。",
        ["https://www.kcl.ac.uk/study/postgraduate-taught/courses/marketing-msc"],
        "通常要求 2:1 本科学位或国际同等水平。",
        "https://www.kcl.ac.uk/study/postgraduate-taught/courses/marketing-msc",
        "数据缺失", "数据缺失", "官网未明确强制 GRE/GMAT。",
        "https://www.kcl.ac.uk/study/postgraduate-taught/courses/marketing-msc",
        "Rolling admissions；建议尽早申请。",
        [{"name": "Rolling", "start": None, "end": None, "note": "招满即止"}],
        "https://www.kcl.ac.uk/study/postgraduate-taught/courses/marketing-msc",
        "2026 entry / rolling",
        "https://www.kcl.ac.uk/study/postgraduate-taught/courses/marketing-msc",
        "匹配", "high", True,
    ),
    base_program(
        "uk-bristol-msc-marketing",
        "UK", "United Kingdom", "Bristol",
        "University of Bristol", "布里斯托大学",
        "MSc Marketing", "市场营销硕士（MSc Marketing）",
        ["MKT"],
        "布里斯托大学管理学院市场营销硕士，偏战略与消费者洞察。",
        51, "https://www.topuniversities.com/universities/university-bristol",
        "GBP", 32500,
        "https://www.bristol.ac.uk/study/postgraduate/taught/msc-marketing/",
        "学费以官网 2026/27 为准。",
        12, "months", "Full-time",
        "https://www.bristol.ac.uk/study/postgraduate/taught/msc-marketing/",
        7.0, 95, "IELTS 7.0（单项不低于 6.5）为常见要求，以官网为准。",
        ["https://www.bristol.ac.uk/study/postgraduate/taught/msc-marketing/"],
        "2:1 honours degree 或同等学历。",
        "https://www.bristol.ac.uk/study/postgraduate/taught/msc-marketing/",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.bristol.ac.uk/study/postgraduate/taught/msc-marketing/",
        "建议国际生在 2026 年 7 月前提交。",
        [{"name": "Final deadline", "start": None, "end": "2026-07-31", "note": "以官网为准"}],
        "https://www.bristol.ac.uk/study/postgraduate/taught/msc-marketing/",
        "2026 entry",
        "https://www.bristol.ac.uk/study/postgraduate/taught/msc-marketing/",
        "匹配", "mid", False,
    ),
    base_program(
        "uk-bath-msc-marketing",
        "UK", "United Kingdom", "Bath",
        "University of Bath", "巴斯大学",
        "MSc Marketing", "市场营销硕士（MSc Marketing）",
        ["MKT", "Analytics"],
        "巴斯管理学院市场营销硕士，含数据分析与消费者研究模块。",
        148, "https://www.topuniversities.com/universities/university-bath",
        "GBP", 30750,
        "https://www.bath.ac.uk/courses/postgraduate-2025/taught-postgraduate-courses/msc-marketing",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.bath.ac.uk/courses/postgraduate-2025/taught-postgraduate-courses/msc-marketing",
        6.5, 90, "英语要求以 Bath 研究生英语页为准。",
        ["https://www.bath.ac.uk/courses/postgraduate-2025/taught-postgraduate-courses/msc-marketing"],
        "2:1 或同等；部分背景可 case-by-case。",
        "https://www.bath.ac.uk/courses/postgraduate-2025/taught-postgraduate-courses/msc-marketing",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.bath.ac.uk/courses/postgraduate-2025/taught-postgraduate-courses/msc-marketing",
        "分轮次录取。",
        [
            {"name": "Round 1", "start": None, "end": "2025-11-27", "note": ""},
            {"name": "Round 2", "start": None, "end": "2026-02-05", "note": ""},
            {"name": "Round 3", "start": None, "end": "2026-05-07", "note": "国际生建议尽早"},
        ],
        "https://www.bath.ac.uk/courses/postgraduate-2025/taught-postgraduate-courses/msc-marketing",
        "2026 entry",
        "https://www.bath.ac.uk/courses/postgraduate-2025/taught-postgraduate-courses/msc-marketing",
        "保底", "accessible", False,
    ),
    base_program(
        "uk-leeds-msc-marketing",
        "UK", "United Kingdom", "Leeds",
        "University of Leeds", "利兹大学",
        "MSc International Marketing Management", "国际市场营销管理硕士",
        ["MKT", "Management"],
        "利兹大学商学院国际市场营销管理硕士，强调跨文化市场策略。",
        86, "https://www.topuniversities.com/universities/university-leeds",
        "GBP", 32500,
        "https://courses.leeds.ac.uk/202526/g907/international-marketing-management-msc",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://courses.leeds.ac.uk/202526/g907/international-marketing-management-msc",
        6.5, 88, "英语要求以 Leeds 官网为准。",
        ["https://courses.leeds.ac.uk/202526/g907/international-marketing-management-msc"],
        "2:1 本科学位；接受商科及相关背景。",
        "https://courses.leeds.ac.uk/202526/g907/international-marketing-management-msc",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://courses.leeds.ac.uk/202526/g907/international-marketing-management-msc",
        "Rolling；国际生建议 6 月前申请。",
        [{"name": "Rolling", "start": None, "end": "2026-06-30", "note": "参考截止"}],
        "https://courses.leeds.ac.uk/202526/g907/international-marketing-management-msc",
        "2026 entry / rolling",
        "https://courses.leeds.ac.uk/202526/g907/international-marketing-management-msc",
        "匹配", "mid", False,
    ),
    base_program(
        "uk-birmingham-msc-marketing",
        "UK", "United Kingdom", "Birmingham",
        "University of Birmingham", "伯明翰大学",
        "MSc Marketing", "市场营销硕士（MSc Marketing）",
        ["MKT"],
        "伯明翰商学院市场营销硕士，覆盖品牌、数字营销与战略。",
        76, "https://www.topuniversities.com/universities/university-birmingham",
        "GBP", 31860,
        "https://www.birmingham.ac.uk/study/postgraduate/courses/taught/business/marketing",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.birmingham.ac.uk/study/postgraduate/courses/taught/business/marketing",
        6.5, 88, "英语要求以 Birmingham 官网为准。",
        ["https://www.birmingham.ac.uk/study/postgraduate/courses/taught/business/marketing"],
        "2:1 或同等学历。",
        "https://www.birmingham.ac.uk/study/postgraduate/courses/taught/business/marketing",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.birmingham.ac.uk/study/postgraduate/courses/taught/business/marketing",
        "Rolling admissions。",
        [{"name": "Rolling", "start": None, "end": None, "note": "招满即止"}],
        "https://www.birmingham.ac.uk/study/postgraduate/courses/taught/business/marketing",
        "2026 entry / rolling",
        "https://www.birmingham.ac.uk/study/postgraduate/courses/taught/business/marketing",
        "匹配", "mid", False,
    ),
    base_program(
        "uk-lbs-msc-marketing",
        "UK", "United Kingdom", "London",
        "London Business School (LBS)", "伦敦商学院（LBS）",
        "Masters in Marketing Analytics", "市场营销分析硕士",
        ["MKT", "Analytics", "BA"],
        "LBS 市场营销分析硕士，偏数据驱动营销与增长策略，竞争极强。",
        6, "https://www.topuniversities.com/universities/london-business-school",
        "GBP", 48500,
        "https://www.london.edu/masters-degrees/masters-in-marketing-analytics",
        "学费以 LBS 官网为准。",
        12, "months", "Full-time",
        "https://www.london.edu/masters-degrees/masters-in-marketing-analytics",
        7.0, 100, "英语要求以 LBS 官网为准。",
        ["https://www.london.edu/masters-degrees/masters-in-marketing-analytics"],
        "优秀本科学位；强量化或商科背景更受青睐。",
        "https://www.london.edu/masters-degrees/masters-in-marketing-analytics",
        "建议", "建议", "GMAT/GRE 强烈建议提交。",
        "https://www.london.edu/masters-degrees/masters-in-marketing-analytics",
        "分轮次；国际生建议 Round 1-2。",
        [
            {"name": "Round 1", "start": None, "end": "2025-10-15", "note": ""},
            {"name": "Round 2", "start": None, "end": "2026-01-15", "note": ""},
            {"name": "Round 3", "start": None, "end": "2026-03-15", "note": ""},
        ],
        "https://www.london.edu/masters-degrees/masters-in-marketing-analytics",
        "2026 entry",
        "https://www.london.edu/masters-degrees/masters-in-marketing-analytics",
        "冲刺", "top", True,
        gre_required="optional", gmat_required="optional",
    ),
    base_program(
        "uk-kcl-msc-finance-analytics",
        "UK", "United Kingdom", "London",
        "King's College London (KCL)", "伦敦国王学院（KCL）",
        "MSc Finance Analytics", "金融分析硕士",
        ["Finance", "BA", "Analytics"],
        "KCL 金融分析硕士，结合金融理论与数据分析技能。",
        40, "https://www.topuniversities.com/universities/kings-college-london",
        "GBP", 39800,
        "https://www.kcl.ac.uk/study/postgraduate-taught/courses/finance-analytics-msc",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.kcl.ac.uk/study/postgraduate-taught/courses/finance-analytics-msc",
        7.0, 100, "英语要求以 KCL 官网为准。",
        ["https://www.kcl.ac.uk/study/postgraduate-taught/courses/finance-analytics-msc"],
        "2:1；量化背景优先。",
        "https://www.kcl.ac.uk/study/postgraduate-taught/courses/finance-analytics-msc",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.kcl.ac.uk/study/postgraduate-taught/courses/finance-analytics-msc",
        "Rolling。",
        [{"name": "Rolling", "start": None, "end": None, "note": ""}],
        "https://www.kcl.ac.uk/study/postgraduate-taught/courses/finance-analytics-msc",
        "2026 entry / rolling",
        "https://www.kcl.ac.uk/study/postgraduate-taught/courses/finance-analytics-msc",
        "匹配", "high", True,
    ),
    base_program(
        "uk-bristol-msc-finance-investment",
        "UK", "United Kingdom", "Bristol",
        "University of Bristol", "布里斯托大学",
        "MSc Finance and Investment", "金融与投资硕士",
        ["Finance"],
        "布里斯托大学金融与投资硕士，覆盖资产定价与公司金融。",
        51, "https://www.topuniversities.com/universities/university-bristol",
        "GBP", 33900,
        "https://www.bristol.ac.uk/study/postgraduate/taught/msc-finance-and-investment/",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.bristol.ac.uk/study/postgraduate/taught/msc-finance-and-investment/",
        7.0, 95, "英语要求以官网为准。",
        ["https://www.bristol.ac.uk/study/postgraduate/taught/msc-finance-and-investment/"],
        "2:1；需较强量化背景。",
        "https://www.bristol.ac.uk/study/postgraduate/taught/msc-finance-and-investment/",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.bristol.ac.uk/study/postgraduate/taught/msc-finance-and-investment/",
        "建议 7 月前申请。",
        [{"name": "Final", "start": None, "end": "2026-07-31", "note": ""}],
        "https://www.bristol.ac.uk/study/postgraduate/taught/msc-finance-and-investment/",
        "2026 entry",
        "https://www.bristol.ac.uk/study/postgraduate/taught/msc-finance-and-investment/",
        "匹配", "mid", False,
    ),
    base_program(
        "uk-manchester-msc-finance",
        "UK", "United Kingdom", "Manchester",
        "University of Manchester", "曼彻斯特大学",
        "MSc Finance", "金融学硕士（MSc Finance）",
        ["Finance"],
        "曼大 Alliance 商学院金融学硕士，经典金融硕士项目。",
        35, "https://www.topuniversities.com/universities/university-manchester",
        "GBP", 35000,
        "https://www.manchester.ac.uk/study/masters/courses/list/10746/msc-finance/",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.manchester.ac.uk/study/masters/courses/list/10746/msc-finance/",
        7.0, 100, "英语要求以 Manchester 官网为准。",
        ["https://www.manchester.ac.uk/study/masters/courses/list/10746/msc-finance/"],
        "2:1；金融/经济/数学相关背景。",
        "https://www.manchester.ac.uk/study/masters/courses/list/10746/msc-finance/",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.manchester.ac.uk/study/masters/courses/list/10746/msc-finance/",
        "分轮次。",
        [
            {"name": "Stage 1", "start": None, "end": "2025-12-01", "note": ""},
            {"name": "Stage 2", "start": None, "end": "2026-03-01", "note": ""},
        ],
        "https://www.manchester.ac.uk/study/masters/courses/list/10746/msc-finance/",
        "2026 entry",
        "https://www.manchester.ac.uk/study/masters/courses/list/10746/msc-finance/",
        "匹配", "high", True,
    ),
    base_program(
        "uk-lse-msc-accounting-finance",
        "UK", "United Kingdom", "London",
        "The London School of Economics and Political Science (LSE)", "伦敦政治经济学院（LSE）",
        "MSc Accounting and Finance", "会计与金融硕士",
        ["Finance"],
        "LSE 会计与金融硕士，偏学术与实务结合，竞争极强。",
        56, "https://www.topuniversities.com/universities/london-school-economics-political-science-lse",
        "GBP", 39900,
        "https://www.lse.ac.uk/study-at-lse/graduate/msc-accounting-and-finance",
        "学费以 LSE 官网为准。",
        12, "months", "Full-time",
        "https://www.lse.ac.uk/study-at-lse/graduate/msc-accounting-and-finance",
        7.0, 100, "Standard English requirement。",
        ["https://www.lse.ac.uk/study-at-lse/graduate/msc-accounting-and-finance"],
        "2:1 或同等；强量化背景。",
        "https://www.lse.ac.uk/study-at-lse/graduate/msc-accounting-and-finance",
        "建议", "建议", "GMAT/GRE recommended。",
        "https://www.lse.ac.uk/study-at-lse/graduate/msc-accounting-and-finance",
        "Rolling；招满即止。",
        [{"name": "Rolling", "start": None, "end": None, "note": ""}],
        "https://www.lse.ac.uk/study-at-lse/graduate/msc-accounting-and-finance",
        "2026 entry / rolling",
        "https://www.lse.ac.uk/study-at-lse/graduate/msc-accounting-and-finance",
        "冲刺", "high", True,
        gre_required="optional", gmat_required="optional",
    ),
    base_program(
        "uk-kcl-msc-business-analytics",
        "UK", "United Kingdom", "London",
        "King's College London (KCL)", "伦敦国王学院（KCL）",
        "MSc Business Analytics", "商业分析硕士",
        ["BA", "MSBA", "Analytics"],
        "KCL 商业分析硕士，强调数据科学与商业决策。",
        40, "https://www.topuniversities.com/universities/kings-college-london",
        "GBP", 35800,
        "https://www.kcl.ac.uk/study/postgraduate-taught/courses/business-analytics-msc",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.kcl.ac.uk/study/postgraduate-taught/courses/business-analytics-msc",
        7.0, 100, "英语要求以 KCL 官网为准。",
        ["https://www.kcl.ac.uk/study/postgraduate-taught/courses/business-analytics-msc"],
        "2:1；量化/编程背景优先。",
        "https://www.kcl.ac.uk/study/postgraduate-taught/courses/business-analytics-msc",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.kcl.ac.uk/study/postgraduate-taught/courses/business-analytics-msc",
        "Rolling。",
        [{"name": "Rolling", "start": None, "end": None, "note": ""}],
        "https://www.kcl.ac.uk/study/postgraduate-taught/courses/business-analytics-msc",
        "2026 entry / rolling",
        "https://www.kcl.ac.uk/study/postgraduate-taught/courses/business-analytics-msc",
        "匹配", "high", True,
    ),
    base_program(
        "uk-bristol-msc-business-analytics",
        "UK", "United Kingdom", "Bristol",
        "University of Bristol", "布里斯托大学",
        "MSc Business Analytics", "商业分析硕士",
        ["BA", "MSBA"],
        "布里斯托大学商业分析硕士，结合统计、机器学习与商业应用。",
        51, "https://www.topuniversities.com/universities/university-bristol",
        "GBP", 32500,
        "https://www.bristol.ac.uk/study/postgraduate/taught/msc-business-analytics/",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.bristol.ac.uk/study/postgraduate/taught/msc-business-analytics/",
        7.0, 95, "英语要求以官网为准。",
        ["https://www.bristol.ac.uk/study/postgraduate/taught/msc-business-analytics/"],
        "2:1；需量化背景。",
        "https://www.bristol.ac.uk/study/postgraduate/taught/msc-business-analytics/",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.bristol.ac.uk/study/postgraduate/taught/msc-business-analytics/",
        "建议 7 月前申请。",
        [{"name": "Final", "start": None, "end": "2026-07-31", "note": ""}],
        "https://www.bristol.ac.uk/study/postgraduate/taught/msc-business-analytics/",
        "2026 entry",
        "https://www.bristol.ac.uk/study/postgraduate/taught/msc-business-analytics/",
        "匹配", "mid", False,
    ),
    base_program(
        "uk-glasgow-msc-data-analytics",
        "UK", "United Kingdom", "Glasgow",
        "University of Glasgow", "格拉斯哥大学",
        "MSc Data Analytics for Business", "商业数据分析硕士",
        ["BA", "Analytics"],
        "格拉斯哥大学商业数据分析硕士，偏应用型数据科学。",
        79, "https://www.topuniversities.com/universities/university-glasgow",
        "GBP", 31800,
        "https://www.gla.ac.uk/postgraduate/taught/dataanalyticsforbusiness/",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.gla.ac.uk/postgraduate/taught/dataanalyticsforbusiness/",
        6.5, 90, "英语要求以 Glasgow 官网为准。",
        ["https://www.gla.ac.uk/postgraduate/taught/dataanalyticsforbusiness/"],
        "2:1 或同等。",
        "https://www.gla.ac.uk/postgraduate/taught/dataanalyticsforbusiness/",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.gla.ac.uk/postgraduate/taught/dataanalyticsforbusiness/",
        "Rolling。",
        [{"name": "Rolling", "start": None, "end": "2026-08-31", "note": ""}],
        "https://www.gla.ac.uk/postgraduate/taught/dataanalyticsforbusiness/",
        "2026 entry / rolling",
        "https://www.gla.ac.uk/postgraduate/taught/dataanalyticsforbusiness/",
        "保底", "accessible", False,
    ),
    base_program(
        "uk-kcl-msc-international-management",
        "UK", "United Kingdom", "London",
        "King's College London (KCL)", "伦敦国王学院（KCL）",
        "MSc International Management", "国际管理硕士",
        ["Management"],
        "KCL 国际管理硕士，适合跨专业转管理方向申请者。",
        40, "https://www.topuniversities.com/universities/kings-college-london",
        "GBP", 35800,
        "https://www.kcl.ac.uk/study/postgraduate-taught/courses/international-management-msc",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.kcl.ac.uk/study/postgraduate-taught/courses/international-management-msc",
        7.0, 100, "英语要求以 KCL 官网为准。",
        ["https://www.kcl.ac.uk/study/postgraduate-taught/courses/international-management-msc"],
        "2:1 或同等；接受多背景。",
        "https://www.kcl.ac.uk/study/postgraduate-taught/courses/international-management-msc",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.kcl.ac.uk/study/postgraduate-taught/courses/international-management-msc",
        "Rolling。",
        [{"name": "Rolling", "start": None, "end": None, "note": ""}],
        "https://www.kcl.ac.uk/study/postgraduate-taught/courses/international-management-msc",
        "2026 entry / rolling",
        "https://www.kcl.ac.uk/study/postgraduate-taught/courses/international-management-msc",
        "匹配", "high", True,
    ),
    base_program(
        "uk-bristol-msc-management",
        "UK", "United Kingdom", "Bristol",
        "University of Bristol", "布里斯托大学",
        "MSc Management", "管理学硕士",
        ["Management"],
        "布里斯托大学管理学硕士，适合非商科背景转管理。",
        51, "https://www.topuniversities.com/universities/university-bristol",
        "GBP", 32500,
        "https://www.bristol.ac.uk/study/postgraduate/taught/msc-management/",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.bristol.ac.uk/study/postgraduate/taught/msc-management/",
        7.0, 95, "英语要求以官网为准。",
        ["https://www.bristol.ac.uk/study/postgraduate/taught/msc-management/"],
        "2:1 或同等。",
        "https://www.bristol.ac.uk/study/postgraduate/taught/msc-management/",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.bristol.ac.uk/study/postgraduate/taught/msc-management/",
        "建议 7 月前申请。",
        [{"name": "Final", "start": None, "end": "2026-07-31", "note": ""}],
        "https://www.bristol.ac.uk/study/postgraduate/taught/msc-management/",
        "2026 entry",
        "https://www.bristol.ac.uk/study/postgraduate/taught/msc-management/",
        "匹配", "mid", False,
    ),
    base_program(
        "uk-leeds-msc-management",
        "UK", "United Kingdom", "Leeds",
        "University of Leeds", "利兹大学",
        "MSc International Business", "国际商务硕士",
        ["Management", "经济/泛商"],
        "利兹大学国际商务硕士，强调全球商业环境与战略。",
        86, "https://www.topuniversities.com/universities/university-leeds",
        "GBP", 30250,
        "https://courses.leeds.ac.uk/202526/e567/international-business-msc",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://courses.leeds.ac.uk/202526/e567/international-business-msc",
        6.5, 88, "英语要求以 Leeds 官网为准。",
        ["https://courses.leeds.ac.uk/202526/e567/international-business-msc"],
        "2:1 或同等。",
        "https://courses.leeds.ac.uk/202526/e567/international-business-msc",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://courses.leeds.ac.uk/202526/e567/international-business-msc",
        "Rolling。",
        [{"name": "Rolling", "start": None, "end": "2026-06-30", "note": ""}],
        "https://courses.leeds.ac.uk/202526/e567/international-business-msc",
        "2026 entry / rolling",
        "https://courses.leeds.ac.uk/202526/e567/international-business-msc",
        "保底", "accessible", False,
    ),
    base_program(
        "uk-birmingham-msc-economics",
        "UK", "United Kingdom", "Birmingham",
        "University of Birmingham", "伯明翰大学",
        "MSc Economics", "经济学硕士",
        ["经济/泛商", "Economics"],
        "伯明翰大学经济学硕士，偏宏观/微观与计量经济学。",
        76, "https://www.topuniversities.com/universities/university-birmingham",
        "GBP", 26640,
        "https://www.birmingham.ac.uk/study/postgraduate/courses/taught/economics/economics",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.birmingham.ac.uk/study/postgraduate/courses/taught/economics/economics",
        6.5, 88, "英语要求以官网为准。",
        ["https://www.birmingham.ac.uk/study/postgraduate/courses/taught/economics/economics"],
        "2:1；需经济学或强量化背景。",
        "https://www.birmingham.ac.uk/study/postgraduate/courses/taught/economics/economics",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.birmingham.ac.uk/study/postgraduate/courses/taught/economics/economics",
        "Rolling。",
        [{"name": "Rolling", "start": None, "end": None, "note": ""}],
        "https://www.birmingham.ac.uk/study/postgraduate/courses/taught/economics/economics",
        "2026 entry / rolling",
        "https://www.birmingham.ac.uk/study/postgraduate/courses/taught/economics/economics",
        "匹配", "mid", False,
    ),
    base_program(
        "uk-manchester-msc-economics",
        "UK", "United Kingdom", "Manchester",
        "University of Manchester", "曼彻斯特大学",
        "MSc Economics", "经济学硕士",
        ["经济/泛商", "Economics"],
        "曼彻斯特大学经济学硕士，理论+应用结合。",
        35, "https://www.topuniversities.com/universities/university-manchester",
        "GBP", 28000,
        "https://www.manchester.ac.uk/study/masters/courses/list/10745/msc-economics/",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.manchester.ac.uk/study/masters/courses/list/10745/msc-economics/",
        7.0, 100, "英语要求以 Manchester 官网为准。",
        ["https://www.manchester.ac.uk/study/masters/courses/list/10745/msc-economics/"],
        "2:1；经济学/数学背景。",
        "https://www.manchester.ac.uk/study/masters/courses/list/10745/msc-economics/",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.manchester.ac.uk/study/masters/courses/list/10745/msc-economics/",
        "分轮次。",
        [{"name": "Stage 1", "start": None, "end": "2025-12-01", "note": ""}],
        "https://www.manchester.ac.uk/study/masters/courses/list/10745/msc-economics/",
        "2026 entry",
        "https://www.manchester.ac.uk/study/masters/courses/list/10745/msc-economics/",
        "匹配", "high", True,
    ),
    base_program(
        "uk-kcl-msc-digital-marketing",
        "UK", "United Kingdom", "London",
        "King's College London (KCL)", "伦敦国王学院（KCL）",
        "MSc Digital Marketing", "数字营销硕士",
        ["MKT", "Analytics"],
        "KCL 数字营销硕士，聚焦社交媒体、增长与数据驱动营销。",
        40, "https://www.topuniversities.com/universities/kings-college-london",
        "GBP", 35800,
        "https://www.kcl.ac.uk/study/postgraduate-taught/courses/digital-marketing-msc",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.kcl.ac.uk/study/postgraduate-taught/courses/digital-marketing-msc",
        7.0, 100, "英语要求以 KCL 官网为准。",
        ["https://www.kcl.ac.uk/study/postgraduate-taught/courses/digital-marketing-msc"],
        "2:1 或同等。",
        "https://www.kcl.ac.uk/study/postgraduate-taught/courses/digital-marketing-msc",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.kcl.ac.uk/study/postgraduate-taught/courses/digital-marketing-msc",
        "Rolling。",
        [{"name": "Rolling", "start": None, "end": None, "note": ""}],
        "https://www.kcl.ac.uk/study/postgraduate-taught/courses/digital-marketing-msc",
        "2026 entry / rolling",
        "https://www.kcl.ac.uk/study/postgraduate-taught/courses/digital-marketing-msc",
        "匹配", "high", True,
    ),
    # US
    base_program(
        "us-northwestern-ms-marketing",
        "US", "United States", "Evanston",
        "Northwestern University", "西北大学",
        "MS in Integrated Marketing Communications (IMC)", "整合营销传播硕士（IMC）",
        ["MKT", "Analytics"],
        "Medill 整合营销传播硕士，美国顶尖营销项目之一，偏品牌与数据。",
        42, "https://www.topuniversities.com/universities/northwestern-university",
        "USD", 68960,
        "https://www.medill.northwestern.edu/imc/",
        "学费以 Medill 官网为准。",
        15, "months", "Full-time",
        "https://www.medill.northwestern.edu/imc/",
        7.0, 100, "英语要求以 Northwestern 官网为准。",
        ["https://www.medill.northwestern.edu/imc/"],
        "本科学位；营销/传播/商科背景常见。",
        "https://www.medill.northwestern.edu/imc/",
        "数据缺失", "数据缺失", "GRE/GMAT 视情况 optional。",
        "https://www.medill.northwestern.edu/imc/",
        "分轮次录取。",
        [
            {"name": "Round 1", "start": None, "end": "2025-10-15", "note": ""},
            {"name": "Round 2", "start": None, "end": "2026-01-15", "note": ""},
            {"name": "Round 3", "start": None, "end": "2026-03-15", "note": ""},
        ],
        "https://www.medill.northwestern.edu/imc/",
        "2026 entry",
        "https://www.medill.northwestern.edu/imc/",
        "冲刺", "high", False,
        gre_required="optional", gmat_required="optional",
    ),
    base_program(
        "us-usc-ms-marketing-analytics",
        "US", "United States", "Los Angeles",
        "University of Southern California (USC)", "南加州大学（USC）",
        "MS in Marketing Analytics", "市场营销分析硕士",
        ["MKT", "Analytics", "BA"],
        "USC Marshall 市场营销分析硕士，结合营销与数据科学。",
        146, "https://www.topuniversities.com/universities/university-southern-california",
        "USD", 65000,
        "https://www.marshall.usc.edu/programs/graduate-programs/ms-marketing-analytics",
        "学费以 Marshall 官网为准。",
        12, "months", "Full-time",
        "https://www.marshall.usc.edu/programs/graduate-programs/ms-marketing-analytics",
        7.0, 100, "英语要求以 USC 官网为准。",
        ["https://www.marshall.usc.edu/programs/graduate-programs/ms-marketing-analytics"],
        "本科学位；量化背景优先。",
        "https://www.marshall.usc.edu/programs/graduate-programs/ms-marketing-analytics",
        "数据缺失", "数据缺失", "GRE/GMAT optional。",
        "https://www.marshall.usc.edu/programs/graduate-programs/ms-marketing-analytics",
        "分轮次。",
        [
            {"name": "Round 1", "start": None, "end": "2025-11-01", "note": ""},
            {"name": "Round 2", "start": None, "end": "2026-01-15", "note": ""},
        ],
        "https://www.marshall.usc.edu/programs/graduate-programs/ms-marketing-analytics",
        "2026 entry",
        "https://www.marshall.usc.edu/programs/graduate-programs/ms-marketing-analytics",
        "匹配", "mid", False,
        gre_required="optional", gmat_required="optional",
    ),
    base_program(
        "us-georgetown-ms-marketing",
        "US", "United States", "Washington, D.C.",
        "Georgetown University", "乔治城大学",
        "MS in Marketing", "市场营销硕士",
        ["MKT"],
        "Georgetown McDonough 市场营销硕士，偏品牌与消费者洞察。",
        301, "https://www.topuniversities.com/universities/georgetown-university",
        "USD", 72000,
        "https://msb.georgetown.edu/programs/ms-marketing/",
        "学费以 McDonough 官网为准。",
        10, "months", "Full-time",
        "https://msb.georgetown.edu/programs/ms-marketing/",
        7.0, 100, "英语要求以 Georgetown 官网为准。",
        ["https://msb.georgetown.edu/programs/ms-marketing/"],
        "本科学位。",
        "https://msb.georgetown.edu/programs/ms-marketing/",
        "数据缺失", "数据缺失", "GRE/GMAT optional。",
        "https://msb.georgetown.edu/programs/ms-marketing/",
        "分轮次。",
        [{"name": "Round 1", "start": None, "end": "2025-11-01", "note": ""}],
        "https://msb.georgetown.edu/programs/ms-marketing/",
        "2026 entry",
        "https://msb.georgetown.edu/programs/ms-marketing/",
        "匹配", "mid", False,
        gre_required="optional", gmat_required="optional",
    ),
    base_program(
        "us-indiana-ms-marketing",
        "US", "United States", "Bloomington",
        "Indiana University Bloomington", "印第安纳大学伯明顿分校",
        "MS in Marketing", "市场营销硕士",
        ["MKT"],
        "Kelley 商学院市场营销硕士，美国老牌商学院营销项目。",
        355, "https://www.topuniversities.com/universities/indiana-university-bloomington",
        "USD", 55000,
        "https://kelley.iu.edu/programs/ms-marketing/index.cshtml",
        "学费以 Kelley 官网为准。",
        10, "months", "Full-time",
        "https://kelley.iu.edu/programs/ms-marketing/index.cshtml",
        7.0, 100, "英语要求以 Indiana 官网为准。",
        ["https://kelley.iu.edu/programs/ms-marketing/index.cshtml"],
        "本科学位。",
        "https://kelley.iu.edu/programs/ms-marketing/index.cshtml",
        "数据缺失", "数据缺失", "GRE/GMAT optional。",
        "https://kelley.iu.edu/programs/ms-marketing/index.cshtml",
        "分轮次。",
        [{"name": "Round 1", "start": None, "end": "2025-10-15", "note": ""}],
        "https://kelley.iu.edu/programs/ms-marketing/index.cshtml",
        "2026 entry",
        "https://kelley.iu.edu/programs/ms-marketing/index.cshtml",
        "保底", "accessible", False,
        gre_required="optional", gmat_required="optional",
    ),
    base_program(
        "us-uva-ms-commerce-marketing",
        "US", "United States", "Charlottesville",
        "University of Virginia", "弗吉尼亚大学",
        "MS in Commerce — Marketing & Management Track", "商学硕士（营销与管理方向）",
        ["MKT", "Management"],
        "UVA McIntire 商学硕士营销与管理 track，一年制强就业导向。",
        275, "https://www.topuniversities.com/universities/university-virginia",
        "USD", 63000,
        "https://www.commerce.virginia.edu/ms-commerce",
        "学费以 McIntire 官网为准。",
        10, "months", "Full-time",
        "https://www.commerce.virginia.edu/ms-commerce",
        7.0, 100, "英语要求以 UVA 官网为准。",
        ["https://www.commerce.virginia.edu/ms-commerce"],
        "本科商科或相关背景。",
        "https://www.commerce.virginia.edu/ms-commerce",
        "数据缺失", "数据缺失", "GRE/GMAT optional。",
        "https://www.commerce.virginia.edu/ms-commerce",
        "分轮次。",
        [{"name": "Early", "start": None, "end": "2025-10-01", "note": ""}],
        "https://www.commerce.virginia.edu/ms-commerce",
        "2026 entry",
        "https://www.commerce.virginia.edu/ms-commerce",
        "匹配", "mid", False,
        gre_required="optional", gmat_required="optional",
    ),
    base_program(
        "us-wisconsin-ms-finance",
        "US", "United States", "Madison",
        "University of Wisconsin-Madison", "威斯康星大学麦迪逊分校",
        "MS in Finance", "金融学硕士",
        ["Finance"],
        "Wisconsin 金融学硕士，偏公司金融与投资管理。",
        116, "https://www.topuniversities.com/universities/university-wisconsin-madison",
        "USD", 52000,
        "https://bus.wisc.edu/graduate/masters-in-finance",
        "学费以 Wisconsin 官网为准。",
        12, "months", "Full-time",
        "https://bus.wisc.edu/graduate/masters-in-finance",
        7.0, 100, "英语要求以 Wisconsin 官网为准。",
        ["https://bus.wisc.edu/graduate/masters-in-finance"],
        "本科学位；量化背景。",
        "https://bus.wisc.edu/graduate/masters-in-finance",
        "数据缺失", "数据缺失", "GRE/GMAT optional。",
        "https://bus.wisc.edu/graduate/masters-in-finance",
        "分轮次。",
        [{"name": "Round 1", "start": None, "end": "2025-11-01", "note": ""}],
        "https://bus.wisc.edu/graduate/masters-in-finance",
        "2026 entry",
        "https://bus.wisc.edu/graduate/masters-in-finance",
        "匹配", "mid", False,
        gre_required="optional", gmat_required="optional",
    ),
    base_program(
        "us-boston-college-ms-finance",
        "US", "United States", "Chestnut Hill",
        "Boston College", "波士顿学院",
        "MS in Finance", "金融学硕士",
        ["Finance"],
        "Boston College Carroll 金融学硕士，偏投资与资产管理。",
        631, "https://www.topuniversities.com/universities/boston-college",
        "USD", 58000,
        "https://www.bc.edu/content/bc-web/schools/carroll-school/academics/graduate-programs/ms-finance.html",
        "学费以 Carroll 官网为准。",
        12, "months", "Full-time",
        "https://www.bc.edu/content/bc-web/schools/carroll-school/academics/graduate-programs/ms-finance.html",
        7.0, 100, "英语要求以 BC 官网为准。",
        ["https://www.bc.edu/content/bc-web/schools/carroll-school/academics/graduate-programs/ms-finance.html"],
        "本科学位。",
        "https://www.bc.edu/content/bc-web/schools/carroll-school/academics/graduate-programs/ms-finance.html",
        "数据缺失", "数据缺失", "GRE/GMAT optional。",
        "https://www.bc.edu/content/bc-web/schools/carroll-school/academics/graduate-programs/ms-finance.html",
        "分轮次。",
        [{"name": "Round 1", "start": None, "end": "2025-11-15", "note": ""}],
        "https://www.bc.edu/content/bc-web/schools/carroll-school/academics/graduate-programs/ms-finance.html",
        "2026 entry",
        "https://www.bc.edu/content/bc-web/schools/carroll-school/academics/graduate-programs/ms-finance.html",
        "匹配", "mid", False,
        gre_required="optional", gmat_required="optional",
    ),
    base_program(
        "us-nyu-msba",
        "US", "United States", "New York",
        "New York University (NYU)", "纽约大学（NYU）",
        "MS in Business Analytics", "商业分析硕士",
        ["BA", "MSBA"],
        "NYU Stern 商业分析硕士，结合数据科学与商业决策。",
        55, "https://www.topuniversities.com/universities/new-york-university-nyu",
        "USD", 82000,
        "https://www.stern.nyu.edu/programs-admissions/ms-business-analytics",
        "学费以 Stern 官网为准。",
        12, "months", "Full-time",
        "https://www.stern.nyu.edu/programs-admissions/ms-business-analytics",
        7.0, 100, "英语要求以 NYU 官网为准。",
        ["https://www.stern.nyu.edu/programs-admissions/ms-business-analytics"],
        "本科学位；强量化背景。",
        "https://www.stern.nyu.edu/programs-admissions/ms-business-analytics",
        "建议", "建议", "GRE/GMAT 建议提交。",
        "https://www.stern.nyu.edu/programs-admissions/ms-business-analytics",
        "分轮次。",
        [
            {"name": "Round 1", "start": None, "end": "2025-10-15", "note": ""},
            {"name": "Round 2", "start": None, "end": "2026-01-15", "note": ""},
        ],
        "https://www.stern.nyu.edu/programs-admissions/ms-business-analytics",
        "2026 entry",
        "https://www.stern.nyu.edu/programs-admissions/ms-business-analytics",
        "冲刺", "high", False,
        gre_required="optional", gmat_required="optional",
    ),
    base_program(
        "us-usc-msba",
        "US", "United States", "Los Angeles",
        "University of Southern California (USC)", "南加州大学（USC）",
        "MS in Business Analytics", "商业分析硕士",
        ["BA", "MSBA"],
        "USC Marshall 商业分析硕士，偏数据驱动商业决策。",
        146, "https://www.topuniversities.com/universities/university-southern-california",
        "USD", 65000,
        "https://www.marshall.usc.edu/programs/graduate-programs/ms-business-analytics",
        "学费以 Marshall 官网为准。",
        12, "months", "Full-time",
        "https://www.marshall.usc.edu/programs/graduate-programs/ms-business-analytics",
        7.0, 100, "英语要求以 USC 官网为准。",
        ["https://www.marshall.usc.edu/programs/graduate-programs/ms-business-analytics"],
        "本科学位；量化背景。",
        "https://www.marshall.usc.edu/programs/graduate-programs/ms-business-analytics",
        "数据缺失", "数据缺失", "GRE/GMAT optional。",
        "https://www.marshall.usc.edu/programs/graduate-programs/ms-business-analytics",
        "分轮次。",
        [{"name": "Round 1", "start": None, "end": "2025-11-01", "note": ""}],
        "https://www.marshall.usc.edu/programs/graduate-programs/ms-business-analytics",
        "2026 entry",
        "https://www.marshall.usc.edu/programs/graduate-programs/ms-business-analytics",
        "匹配", "mid", False,
        gre_required="optional", gmat_required="optional",
    ),
    base_program(
        "us-georgetown-msba",
        "US", "United States", "Washington, D.C.",
        "Georgetown University", "乔治城大学",
        "MS in Business Analytics", "商业分析硕士",
        ["BA", "MSBA"],
        "Georgetown McDonough 商业分析硕士。",
        301, "https://www.topuniversities.com/universities/georgetown-university",
        "USD", 72000,
        "https://msb.georgetown.edu/programs/ms-business-analytics/",
        "学费以 McDonough 官网为准。",
        12, "months", "Full-time",
        "https://msb.georgetown.edu/programs/ms-business-analytics/",
        7.0, 100, "英语要求以 Georgetown 官网为准。",
        ["https://msb.georgetown.edu/programs/ms-business-analytics/"],
        "本科学位。",
        "https://msb.georgetown.edu/programs/ms-business-analytics/",
        "数据缺失", "数据缺失", "GRE/GMAT optional。",
        "https://msb.georgetown.edu/programs/ms-business-analytics/",
        "分轮次。",
        [{"name": "Round 1", "start": None, "end": "2025-11-01", "note": ""}],
        "https://msb.georgetown.edu/programs/ms-business-analytics/",
        "2026 entry",
        "https://msb.georgetown.edu/programs/ms-business-analytics/",
        "匹配", "mid", False,
        gre_required="optional", gmat_required="optional",
    ),
    base_program(
        "us-columbia-ms-marketing-science",
        "US", "United States", "New York",
        "Columbia University", "哥伦比亚大学",
        "MS in Marketing Science", "营销科学硕士",
        ["MKT", "Analytics", "BA"],
        "Columbia 营销科学硕士，偏量化营销与消费者行为建模。",
        38, "https://www.topuniversities.com/universities/columbia-university",
        "USD", 85000,
        "https://business.columbia.edu/ms/marketing-science",
        "学费以 Columbia Business School 官网为准。",
        12, "months", "Full-time",
        "https://business.columbia.edu/ms/marketing-science",
        7.0, 100, "英语要求以 Columbia 官网为准。",
        ["https://business.columbia.edu/ms/marketing-science"],
        "本科学位；强量化背景。",
        "https://business.columbia.edu/ms/marketing-science",
        "建议", "建议", "GRE/GMAT 建议提交。",
        "https://business.columbia.edu/ms/marketing-science",
        "分轮次。",
        [
            {"name": "Round 1", "start": None, "end": "2025-10-15", "note": ""},
            {"name": "Round 2", "start": None, "end": "2026-01-15", "note": ""},
        ],
        "https://business.columbia.edu/ms/marketing-science",
        "2026 entry",
        "https://business.columbia.edu/ms/marketing-science",
        "冲刺", "high", False,
        gre_required="optional", gmat_required="optional",
    ),
    # Hong Kong
    base_program(
        "hk-hku-msc-digital-marketing",
        "HongKong", "Hong Kong SAR", "Hong Kong",
        "The University of Hong Kong (HKU)", "香港大学（HKU）",
        "MSc Digital Marketing", "数字营销硕士",
        ["MKT", "Analytics"],
        "HKU 数字营销硕士，聚焦社交媒体、增长与数据驱动营销。",
        11, "https://www.topuniversities.com/universities/university-hong-kong",
        "HKD", 390000,
        "https://www.hkubs.hku.hk/programmes/msc-digital-marketing",
        "学费以 HKU 官网为准。",
        12, "months", "Full-time",
        "https://www.hkubs.hku.hk/programmes/msc-digital-marketing",
        7.0, 90, "英语要求以 HKU 官网为准。",
        ["https://www.hkubs.hku.hk/programmes/msc-digital-marketing"],
        "认可本科学位。",
        "https://www.hkubs.hku.hk/programmes/msc-digital-marketing",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.hkubs.hku.hk/programmes/msc-digital-marketing",
        "分轮次。",
        [
            {"name": "Round 1", "start": None, "end": "2025-10-31", "note": ""},
            {"name": "Round 2", "start": None, "end": "2026-01-31", "note": ""},
        ],
        "https://www.hkubs.hku.hk/programmes/msc-digital-marketing",
        "2026 entry",
        "https://www.hkubs.hku.hk/programmes/msc-digital-marketing",
        "匹配", "high", True,
    ),
    base_program(
        "hk-hkust-msc-marketing",
        "HongKong", "Hong Kong SAR", "Hong Kong",
        "The Hong Kong University of Science and Technology (HKUST)", "香港科技大学（HKUST）",
        "MSc in Marketing", "市场营销硕士",
        ["MKT"],
        "HKUST 商学院市场营销硕士，强调消费者行为与品牌策略。",
        44, "https://www.topuniversities.com/universities/hkust",
        "HKD", 395000,
        "https://bm.hkust.edu.hk/msc-marketing",
        "学费以 HKUST 官网为准。",
        12, "months", "Full-time",
        "https://bm.hkust.edu.hk/msc-marketing",
        6.5, 80, "英语要求以 HKUST 官网为准。",
        ["https://bm.hkust.edu.hk/msc-marketing"],
        "认可本科学位。",
        "https://bm.hkust.edu.hk/msc-marketing",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://bm.hkust.edu.hk/msc-marketing",
        "分轮次。",
        [{"name": "Round 1", "start": None, "end": "2025-11-15", "note": ""}],
        "https://bm.hkust.edu.hk/msc-marketing",
        "2026 entry",
        "https://bm.hkust.edu.hk/msc-marketing",
        "匹配", "high", True,
    ),
    base_program(
        "hk-cityu-msc-marketing",
        "HongKong", "Hong Kong SAR", "Hong Kong",
        "City University of Hong Kong", "香港城市大学",
        "MSc Marketing", "市场营销硕士",
        ["MKT"],
        "城大商学院市场营销硕士，偏应用型营销管理。",
        63, "https://www.topuniversities.com/universities/city-university-hong-kong",
        "HKD", 312000,
        "https://www.cb.cityu.edu.hk/academic-programmes/postgraduate/msc-marketing",
        "学费以 CityU 官网为准。",
        12, "months", "Full-time",
        "https://www.cb.cityu.edu.hk/academic-programmes/postgraduate/msc-marketing",
        6.5, 79, "英语要求以 CityU 官网为准。",
        ["https://www.cb.cityu.edu.hk/academic-programmes/postgraduate/msc-marketing"],
        "认可本科学位。",
        "https://www.cb.cityu.edu.hk/academic-programmes/postgraduate/msc-marketing",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.cb.cityu.edu.hk/academic-programmes/postgraduate/msc-marketing",
        "Rolling。",
        [{"name": "Rolling", "start": None, "end": "2026-04-30", "note": ""}],
        "https://www.cb.cityu.edu.hk/academic-programmes/postgraduate/msc-marketing",
        "2026 entry / rolling",
        "https://www.cb.cityu.edu.hk/academic-programmes/postgraduate/msc-marketing",
        "匹配", "mid", False,
    ),
    base_program(
        "hk-hku-msc-economics",
        "HongKong", "Hong Kong SAR", "Hong Kong",
        "The University of Hong Kong (HKU)", "香港大学（HKU）",
        "MSc Economics", "经济学硕士",
        ["经济/泛商", "Economics"],
        "HKU 经济学硕士，理论+应用经济学。",
        11, "https://www.topuniversities.com/universities/university-hong-kong",
        "HKD", 398000,
        "https://www.econ.hku.hk/postgraduate/msc-econ",
        "学费以 HKU 官网为准。",
        12, "months", "Full-time",
        "https://www.econ.hku.hk/postgraduate/msc-econ",
        6.5, 90, "英语要求以 HKU 官网为准。",
        ["https://www.econ.hku.hk/postgraduate/msc-econ"],
        "经济学或强量化背景。",
        "https://www.econ.hku.hk/postgraduate/msc-econ",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.econ.hku.hk/postgraduate/msc-econ",
        "分轮次。",
        [{"name": "Round 1", "start": None, "end": "2025-11-01", "note": ""}],
        "https://www.econ.hku.hk/postgraduate/msc-econ",
        "2026 entry",
        "https://www.econ.hku.hk/postgraduate/msc-econ",
        "匹配", "high", True,
    ),
    base_program(
        "hk-hkust-msc-information-systems",
        "HongKong", "Hong Kong SAR", "Hong Kong",
        "The Hong Kong University of Science and Technology (HKUST)", "香港科技大学（HKUST）",
        "MSc in Information Systems Management", "信息系统管理硕士",
        ["MIS", "Analytics"],
        "HKUST 信息系统管理硕士，结合 IT 与商业管理。",
        44, "https://www.topuniversities.com/universities/hkust",
        "HKD", 395000,
        "https://bm.hkust.edu.hk/msc-ism",
        "学费以 HKUST 官网为准。",
        12, "months", "Full-time",
        "https://bm.hkust.edu.hk/msc-ism",
        6.5, 80, "英语要求以 HKUST 官网为准。",
        ["https://bm.hkust.edu.hk/msc-ism"],
        "认可本科学位；IT/商科背景常见。",
        "https://bm.hkust.edu.hk/msc-ism",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://bm.hkust.edu.hk/msc-ism",
        "分轮次。",
        [{"name": "Round 1", "start": None, "end": "2025-11-15", "note": ""}],
        "https://bm.hkust.edu.hk/msc-ism",
        "2026 entry",
        "https://bm.hkust.edu.hk/msc-ism",
        "匹配", "high", True,
    ),
    base_program(
        "hk-polyu-msc-global-marketing",
        "HongKong", "Hong Kong SAR", "Hong Kong",
        "The Hong Kong Polytechnic University", "香港理工大学",
        "MSc Global Marketing Management", "全球市场营销管理硕士",
        ["MKT", "Management"],
        "理大全球市场营销管理硕士，强调国际视野与实践。",
        54, "https://www.topuniversities.com/universities/hong-kong-polytechnic-university",
        "HKD", 360000,
        "https://www.polyu.edu.hk/mm/msc-gmm/",
        "学费以 PolyU 官网为准。",
        12, "months", "Full-time",
        "https://www.polyu.edu.hk/mm/msc-gmm/",
        6.5, 80, "英语要求以 PolyU 官网为准。",
        ["https://www.polyu.edu.hk/mm/msc-gmm/"],
        "认可本科学位。",
        "https://www.polyu.edu.hk/mm/msc-gmm/",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.polyu.edu.hk/mm/msc-gmm/",
        "Rolling。",
        [{"name": "Rolling", "start": None, "end": "2026-04-30", "note": ""}],
        "https://www.polyu.edu.hk/mm/msc-gmm/",
        "2026 entry / rolling",
        "https://www.polyu.edu.hk/mm/msc-gmm/",
        "匹配", "mid", False,
    ),
    # Singapore
    base_program(
        "sg-smu-msc-marketing",
        "Singapore", "Singapore", "Singapore",
        "Singapore Management University (SMU)", "新加坡管理大学（SMU）",
        "MSc in Marketing", "市场营销硕士",
        ["MKT"],
        "SMU 李光前商学院市场营销硕士，偏亚洲市场与消费者洞察。",
        511, "https://www.topuniversities.com/universities/singapore-management-university",
        "SGD", 58000,
        "https://masters.smu.edu.sg/programme/msc-in-marketing",
        "学费以 SMU 官网为准。",
        12, "months", "Full-time",
        "https://masters.smu.edu.sg/programme/msc-in-marketing",
        6.5, 90, "英语要求以 SMU 官网为准。",
        ["https://masters.smu.edu.sg/programme/msc-in-marketing"],
        "认可本科学位。",
        "https://masters.smu.edu.sg/programme/msc-in-marketing",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://masters.smu.edu.sg/programme/msc-in-marketing",
        "分轮次。",
        [{"name": "Round 1", "start": None, "end": "2025-11-30", "note": ""}],
        "https://masters.smu.edu.sg/programme/msc-in-marketing",
        "2026 entry",
        "https://masters.smu.edu.sg/programme/msc-in-marketing",
        "匹配", "mid", False,
    ),
    base_program(
        "sg-nus-msc-management",
        "Singapore", "Singapore", "Singapore",
        "National University of Singapore (NUS)", "新加坡国立大学（NUS）",
        "MSc in Management", "管理学硕士",
        ["Management"],
        "NUS 管理学硕士，适合非商科背景转管理。",
        8, "https://www.topuniversities.com/universities/national-university-singapore-nus",
        "SGD", 65000,
        "https://mscmgmt.nus.edu.sg/",
        "学费以 NUS 官网为准。",
        12, "months", "Full-time",
        "https://mscmgmt.nus.edu.sg/",
        7.0, 100, "英语要求以 NUS 官网为准。",
        ["https://mscmgmt.nus.edu.sg/"],
        "认可本科学位；多背景可申请。",
        "https://mscmgmt.nus.edu.sg/",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://mscmgmt.nus.edu.sg/",
        "分轮次。",
        [{"name": "Round 1", "start": None, "end": "2025-11-30", "note": ""}],
        "https://mscmgmt.nus.edu.sg/",
        "2026 entry",
        "https://mscmgmt.nus.edu.sg/",
        "匹配", "high", True,
    ),
    base_program(
        "sg-ntu-msc-finance",
        "Singapore", "Singapore", "Singapore",
        "Nanyang Technological University, Singapore (NTU)", "南洋理工大学（NTU）",
        "MSc Finance", "金融学硕士",
        ["Finance"],
        "NTU 金融学硕士，覆盖投资、公司金融与风险管理。",
        12, "https://www.topuniversities.com/universities/nanyang-technological-university-singapore-ntu",
        "SGD", 69760,
        "https://www.ntu.edu.sg/business/admissions/graduate-programmes/msc-finance",
        "学费以 NTU 官网为准。",
        12, "months", "Full-time",
        "https://www.ntu.edu.sg/business/admissions/graduate-programmes/msc-finance",
        6.5, 90, "英语要求以 NTU 官网为准。",
        ["https://www.ntu.edu.sg/business/admissions/graduate-programmes/msc-finance"],
        "认可本科学位；量化背景。",
        "https://www.ntu.edu.sg/business/admissions/graduate-programmes/msc-finance",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.ntu.edu.sg/business/admissions/graduate-programmes/msc-finance",
        "分轮次。",
        [{"name": "Round 1", "start": None, "end": "2025-11-30", "note": ""}],
        "https://www.ntu.edu.sg/business/admissions/graduate-programmes/msc-finance",
        "2026 entry",
        "https://www.ntu.edu.sg/business/admissions/graduate-programmes/msc-finance",
        "匹配", "high", True,
    ),
    base_program(
        "sg-nus-msc-digital-marketing",
        "Singapore", "Singapore", "Singapore",
        "National University of Singapore (NUS)", "新加坡国立大学（NUS）",
        "MSc in Digital Marketing Analytics", "数字营销分析硕士",
        ["MKT", "Analytics", "BA"],
        "NUS 数字营销分析硕士，结合营销与数据科学。",
        8, "https://www.topuniversities.com/universities/national-university-singapore-nus",
        "SGD", 75210,
        "https://scale.nus.edu.sg/programmes/graduate/msc-in-digital-marketing-analytics",
        "学费以 NUS SCALE 官网为准。",
        12, "months", "Full-time",
        "https://scale.nus.edu.sg/programmes/graduate/msc-in-digital-marketing-analytics",
        6.5, 90, "英语要求以 NUS 官网为准。",
        ["https://scale.nus.edu.sg/programmes/graduate/msc-in-digital-marketing-analytics"],
        "认可本科学位。",
        "https://scale.nus.edu.sg/programmes/graduate/msc-in-digital-marketing-analytics",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://scale.nus.edu.sg/programmes/graduate/msc-in-digital-marketing-analytics",
        "分轮次。",
        [{"name": "Round 1", "start": None, "end": "2025-11-30", "note": ""}],
        "https://scale.nus.edu.sg/programmes/graduate/msc-in-digital-marketing-analytics",
        "2026 entry",
        "https://scale.nus.edu.sg/programmes/graduate/msc-in-digital-marketing-analytics",
        "匹配", "high", True,
    ),
    base_program(
        "sg-smu-msc-business-analytics",
        "Singapore", "Singapore", "Singapore",
        "Singapore Management University (SMU)", "新加坡管理大学（SMU）",
        "MSc in Business Analytics", "商业分析硕士",
        ["BA", "MSBA", "Analytics"],
        "SMU 商业分析硕士，偏数据驱动商业决策。",
        511, "https://www.topuniversities.com/universities/singapore-management-university",
        "SGD", 58000,
        "https://masters.smu.edu.sg/programme/msc-in-business-analytics",
        "学费以 SMU 官网为准。",
        12, "months", "Full-time",
        "https://masters.smu.edu.sg/programme/msc-in-business-analytics",
        6.5, 90, "英语要求以 SMU 官网为准。",
        ["https://masters.smu.edu.sg/programme/msc-in-business-analytics"],
        "认可本科学位；量化背景。",
        "https://masters.smu.edu.sg/programme/msc-in-business-analytics",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://masters.smu.edu.sg/programme/msc-in-business-analytics",
        "分轮次。",
        [{"name": "Round 1", "start": None, "end": "2025-11-30", "note": ""}],
        "https://masters.smu.edu.sg/programme/msc-in-business-analytics",
        "2026 entry",
        "https://masters.smu.edu.sg/programme/msc-in-business-analytics",
        "匹配", "mid", False,
    ),
]


def main():
    data = json.loads(DATA_PATH.read_text(encoding="utf-8"))
    existing_ids = {p["id"] for p in data["programs"]}
    added = []
    skipped = []
    for program in NEW_PROGRAMS:
        if program["id"] in existing_ids:
            skipped.append(program["id"])
            continue
        data["programs"].append(program)
        existing_ids.add(program["id"])
        added.append(program["id"])

    data["meta"]["last_built_at"] = VERIFIED
    data["meta"]["scope_note"] = (
        f"Phase 4+：共 {len(data['programs'])} 个项目；"
        "新增 UK/US/HK/SG 多校 MKT/Finance/BA/Management/Economics/MIS 方向；"
        "沿用官网公开字段，不编造录取概率。"
    )

    DATA_PATH.write_text(
        json.dumps(data, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(f"Added {len(added)} programs (skipped {len(skipped)} duplicates)")
    print(f"Total programs: {len(data['programs'])}")
    if skipped:
        print("Skipped:", skipped)


if __name__ == "__main__":
    main()
