#!/usr/bin/env python3
"""Add DataScience / Media / HCI programs and refresh meta."""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(Path(__file__).resolve().parent))
from add_programs_batch import base_program, VERIFIED  # noqa: E402
from add_multidisciplinary_programs import merge_inferred_tags  # noqa: E402

DATA_PATH = ROOT / "data" / "programs.json"

NEW_PROGRAMS = [
    # ── DataScience ─────────────────────────────────────────────
    base_program(
        "uk-oxford-msc-statistical-science",
        "UK", "United Kingdom", "Oxford",
        "University of Oxford", "牛津大学",
        "MSc in Statistical Science", "统计科学理学硕士",
        ["DataScience"],
        "牛津统计系 MSc，机器学习、贝叶斯与大规模数据分析。",
        3, "https://www.topuniversities.com/universities/university-oxford",
        "GBP", 32520,
        "https://www.ox.ac.uk/admissions/graduate/courses/msc-statistical-science",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.ox.ac.uk/admissions/graduate/courses/msc-statistical-science",
        7.5, 110, "英语要求以 Oxford 官网为准。",
        ["https://www.ox.ac.uk/admissions/graduate/courses/msc-statistical-science"],
        "强量化本科背景；数学/统计/CS 优先。",
        "https://www.ox.ac.uk/admissions/graduate/courses/msc-statistical-science",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.ox.ac.uk/admissions/graduate/courses/msc-statistical-science",
        "分轮次。",
        [{"name": "Jan deadline", "start": None, "end": "2026-01-08", "note": "参考"}],
        "https://www.ox.ac.uk/admissions/graduate/courses/msc-statistical-science",
        "2026 entry",
        "https://www.ox.ac.uk/admissions/graduate/courses/msc-statistical-science",
        "冲刺", "top", True,
    ),
    base_program(
        "uk-cambridge-mphil-mlmi",
        "UK", "United Kingdom", "Cambridge",
        "University of Cambridge", "剑桥大学",
        "MPhil in Machine Learning and Machine Intelligence", "机器学习与机器智能 MPhil",
        ["DataScience", "CS"],
        "剑桥工程系 MLMI，深度学习、强化学习与 AI 系统。",
        5, "https://www.topuniversities.com/universities/university-cambridge",
        "GBP", 35000,
        "https://www.postgraduate.study.cam.ac.uk/courses/directory/egegmpmml",
        "学费以官网为准。",
        11, "months", "Full-time",
        "https://www.postgraduate.study.cam.ac.uk/courses/directory/egegmpmml",
        7.5, 110, "英语要求以 Cambridge 官网为准。",
        ["https://www.postgraduate.study.cam.ac.uk/courses/directory/egegmpmml"],
        "一等或强 2:1 STEM；编程与数学要求高。",
        "https://www.postgraduate.study.cam.ac.uk/courses/directory/egegmpmml",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.postgraduate.study.cam.ac.uk/courses/directory/egegmpmml",
        "分轮次。",
        [{"name": "Round", "start": None, "end": "2026-01-02", "note": "参考"}],
        "https://www.postgraduate.study.cam.ac.uk/courses/directory/egegmpmml",
        "2026 entry",
        "https://www.postgraduate.study.cam.ac.uk/courses/directory/egegmpmml",
        "冲刺", "top", True,
    ),
    base_program(
        "uk-kcl-msc-data-science",
        "UK", "United Kingdom", "London",
        "King's College London (KCL)", "伦敦国王学院（KCL）",
        "MSc Data Science", "数据科学硕士",
        ["DataScience"],
        "KCL 数据科学 MSc，统计建模、机器学习与可视化。",
        40, "https://www.topuniversities.com/universities/kings-college-london",
        "GBP", 33250,
        "https://www.kcl.ac.uk/study/postgraduate-taught/courses/data-science-msc",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.kcl.ac.uk/study/postgraduate-taught/courses/data-science-msc",
        7.0, 100, "英语要求以 KCL 官网为准。",
        ["https://www.kcl.ac.uk/study/postgraduate-taught/courses/data-science-msc"],
        "2:1 量化或计算相关背景。",
        "https://www.kcl.ac.uk/study/postgraduate-taught/courses/data-science-msc",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.kcl.ac.uk/study/postgraduate-taught/courses/data-science-msc",
        "Rolling。",
        [{"name": "Rolling", "start": None, "end": None, "note": ""}],
        "https://www.kcl.ac.uk/study/postgraduate-taught/courses/data-science-msc",
        "2026 entry / rolling",
        "https://www.kcl.ac.uk/study/postgraduate-taught/courses/data-science-msc",
        "匹配", "high", True,
    ),
    base_program(
        "uk-edinburgh-msc-statistics-data-science",
        "UK", "United Kingdom", "Edinburgh",
        "The University of Edinburgh", "爱丁堡大学",
        "MSc Statistics and Data Science", "统计与数据科学硕士",
        ["DataScience"],
        "爱丁堡数学系统计与数据科学 MSc，含机器学习与统计推断。",
        34, "https://www.topuniversities.com/universities/university-edinburgh",
        "GBP", 28000,
        "https://www.ed.ac.uk/studying/postgraduate/degrees/statistics-data-science-msc",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.ed.ac.uk/studying/postgraduate/degrees/statistics-data-science-msc",
        7.0, 100, "英语要求以官网为准。",
        ["https://www.ed.ac.uk/studying/postgraduate/degrees/statistics-data-science-msc"],
        "2:1 数学、统计或相关量化背景。",
        "https://www.ed.ac.uk/studying/postgraduate/degrees/statistics-data-science-msc",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.ed.ac.uk/studying/postgraduate/degrees/statistics-data-science-msc",
        "分轮次。",
        [{"name": "Round 3", "start": None, "end": "2026-05-14", "note": ""}],
        "https://www.ed.ac.uk/studying/postgraduate/degrees/statistics-data-science-msc",
        "2026 entry",
        "https://www.ed.ac.uk/studying/postgraduate/degrees/statistics-data-science-msc",
        "匹配", "high", False,
    ),
    base_program(
        "uk-manchester-msc-data-science",
        "UK", "United Kingdom", "Manchester",
        "The University of Manchester", "曼彻斯特大学",
        "MSc Data Science", "数据科学硕士",
        ["DataScience"],
        "曼大数据科学 MSc，Python、机器学习与大数据工程。",
        35, "https://www.topuniversities.com/universities/university-manchester",
        "GBP", 31000,
        "https://www.manchester.ac.uk/study/masters/courses/list/09683/msc-data-science/",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.manchester.ac.uk/study/masters/courses/list/09683/msc-data-science/",
        7.0, 100, "英语要求以官网为准。",
        ["https://www.manchester.ac.uk/study/masters/courses/list/09683/msc-data-science/"],
        "2:1 STEM 或相关背景。",
        "https://www.manchester.ac.uk/study/masters/courses/list/09683/msc-data-science/",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.manchester.ac.uk/study/masters/courses/list/09683/msc-data-science/",
        "Rolling。",
        [{"name": "Rolling", "start": None, "end": None, "note": ""}],
        "https://www.manchester.ac.uk/study/masters/courses/list/09683/msc-data-science/",
        "2026 entry / rolling",
        "https://www.manchester.ac.uk/study/masters/courses/list/09683/msc-data-science/",
        "匹配", "high", False,
    ),
    base_program(
        "uk-warwick-msc-statistics",
        "UK", "United Kingdom", "Coventry",
        "University of Warwick", "华威大学",
        "MSc Statistics", "统计学硕士",
        ["DataScience"],
        "华威统计系 MSc，数据挖掘、机器学习与统计建模。",
        74, "https://www.topuniversities.com/universities/university-warwick",
        "GBP", 30750,
        "https://warwick.ac.uk/study/postgraduate/courses/msc-statistics",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://warwick.ac.uk/study/postgraduate/courses/msc-statistics",
        6.5, 92, "英语要求以 Warwick 官网为准。",
        ["https://warwick.ac.uk/study/postgraduate/courses/msc-statistics"],
        "2:1 数学或统计相关背景。",
        "https://warwick.ac.uk/study/postgraduate/courses/msc-statistics",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://warwick.ac.uk/study/postgraduate/courses/msc-statistics",
        "Rolling。",
        [{"name": "Rolling", "start": None, "end": None, "note": ""}],
        "https://warwick.ac.uk/study/postgraduate/courses/msc-statistics",
        "2026 entry / rolling",
        "https://warwick.ac.uk/study/postgraduate/courses/msc-statistics",
        "匹配", "mid", False,
    ),
    base_program(
        "us-berkeley-mids",
        "US", "United States", "Berkeley",
        "University of California, Berkeley", "加州大学伯克利分校（Berkeley）",
        "Master of Information and Data Science (MIDS)", "信息学与数据科学硕士（MIDS）",
        ["DataScience"],
        "Berkeley I School MIDS，在线/混合可选；数据工程、ML 与可视化。",
        12, "https://www.topuniversities.com/universities/university-california-berkeley-ucb",
        "USD", 75000,
        "https://ischoolonline.berkeley.edu/data-science/",
        "学费以官网为准。",
        20, "months", "Part-time / online options",
        "https://ischoolonline.berkeley.edu/data-science/",
        7.0, 100, "英语要求以 Berkeley 官网为准。",
        ["https://ischoolonline.berkeley.edu/data-science/"],
        "本科任意背景；量化与编程经历重要。",
        "https://ischoolonline.berkeley.edu/data-science/",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://ischoolonline.berkeley.edu/data-science/",
        "分轮次。",
        [{"name": "Round 1", "start": None, "end": "2026-01-15", "note": "参考"}],
        "https://ischoolonline.berkeley.edu/data-science/",
        "2026 entry",
        "https://ischoolonline.berkeley.edu/data-science/",
        "冲刺", "top", True,
    ),
    base_program(
        "us-cmu-msds",
        "US", "United States", "Pittsburgh",
        "Carnegie Mellon University (CMU)", "卡内基梅隆大学（CMU）",
        "Master of Science in Data Science (MSDS)", "数据科学理学硕士（MSDS）",
        ["DataScience", "CS"],
        "CMU 数据科学硕士，统计、机器学习与大规模系统。",
        52, "https://www.topuniversities.com/universities/carnegie-mellon-university",
        "USD", 58000,
        "https://www.cmu.edu/datascience-academics/msds/index.html",
        "学费以官网为准。",
        16, "months", "Full-time",
        "https://www.cmu.edu/datascience-academics/msds/index.html",
        7.0, 100, "英语要求以 CMU 官网为准。",
        ["https://www.cmu.edu/datascience-academics/msds/index.html"],
        "强 STEM 本科；数学与编程要求高。",
        "https://www.cmu.edu/datascience-academics/msds/index.html",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.cmu.edu/datascience-academics/msds/index.html",
        "分轮次。",
        [{"name": "Round 1", "start": None, "end": "2025-12-15", "note": "参考"}],
        "https://www.cmu.edu/datascience-academics/msds/index.html",
        "2026 entry",
        "https://www.cmu.edu/datascience-academics/msds/index.html",
        "冲刺", "top", True,
    ),
    base_program(
        "us-duke-mids",
        "US", "United States", "Durham",
        "Duke University", "杜克大学",
        "Master in Interdisciplinary Data Science (MIDS)", "跨学科数据科学硕士（MIDS）",
        ["DataScience"],
        "杜克 MIDS，统计、CS 与社会科学交叉的数据科学训练。",
        61, "https://www.topuniversities.com/universities/duke-university",
        "USD", 65000,
        "https://datascience.duke.edu/academics/masters-in-data-science/",
        "学费以官网为准。",
        24, "months", "Full-time",
        "https://datascience.duke.edu/academics/masters-in-data-science/",
        7.0, 100, "英语要求以 Duke 官网为准。",
        ["https://datascience.duke.edu/academics/masters-in-data-science/"],
        "本科任意背景；量化课程与项目经历重要。",
        "https://datascience.duke.edu/academics/masters-in-data-science/",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://datascience.duke.edu/academics/masters-in-data-science/",
        "分轮次。",
        [{"name": "Round 1", "start": None, "end": "2026-01-15", "note": "参考"}],
        "https://datascience.duke.edu/academics/masters-in-data-science/",
        "2026 entry",
        "https://datascience.duke.edu/academics/masters-in-data-science/",
        "冲刺", "top", True,
    ),
    base_program(
        "us-ucla-ms-dse",
        "US", "United States", "Los Angeles",
        "University of California, Los Angeles (UCLA)", "加州大学洛杉矶分校（UCLA）",
        "Master of Science in Data Science Engineering", "数据科学工程硕士",
        ["DataScience", "CS"],
        "UCLA Samueli 数据科学工程 MS，大数据系统与机器学习应用。",
        46, "https://www.topuniversities.com/universities/university-california-los-angeles-ucla",
        "USD", 52000,
        "https://www.seasoasa.ucla.edu/graduate-programs/data-science-engineering",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.seasoasa.ucla.edu/graduate-programs/data-science-engineering",
        7.0, 100, "英语要求以 UCLA 官网为准。",
        ["https://www.seasoasa.ucla.edu/graduate-programs/data-science-engineering"],
        "工程或量化 STEM 背景。",
        "https://www.seasoasa.ucla.edu/graduate-programs/data-science-engineering",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.seasoasa.ucla.edu/graduate-programs/data-science-engineering",
        "分轮次。",
        [{"name": "Round 1", "start": None, "end": "2026-12-01", "note": "参考"}],
        "https://www.seasoasa.ucla.edu/graduate-programs/data-science-engineering",
        "2026 entry",
        "https://www.seasoasa.ucla.edu/graduate-programs/data-science-engineering",
        "匹配", "high", False,
    ),
    base_program(
        "hk-hku-msc-data-science",
        "HongKong", "Hong Kong SAR", "Hong Kong",
        "The University of Hong Kong (HKU)", "香港大学（HKU）",
        "MSc in Data Science", "数据科学理学硕士",
        ["DataScience"],
        "港大统计与精算系数据科学 MSc，统计学习与 AI 应用。",
        26, "https://www.topuniversities.com/universities/university-hong-kong",
        "HKD", 288000,
        "https://www.saasweb.hku.hk/programmes/msc-ds",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.saasweb.hku.hk/programmes/msc-ds",
        6.5, 80, "英语要求以 HKU 官网为准。",
        ["https://www.saasweb.hku.hk/programmes/msc-ds"],
        "量化或 STEM 本科背景。",
        "https://www.saasweb.hku.hk/programmes/msc-ds",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.saasweb.hku.hk/programmes/msc-ds",
        "分轮次。",
        [{"name": "Main Round", "start": None, "end": "2026-02-28", "note": "参考"}],
        "https://www.saasweb.hku.hk/programmes/msc-ds",
        "2026 entry",
        "https://www.saasweb.hku.hk/programmes/msc-ds",
        "冲刺", "top", True,
    ),
    base_program(
        "hk-cuhk-msc-data-science",
        "HongKong", "Hong Kong SAR", "Hong Kong",
        "The Chinese University of Hong Kong (CUHK)", "香港中文大学（CUHK）",
        "MSc in Data Science", "数据科学理学硕士",
        ["DataScience"],
        "中大数据科学 MSc，统计、机器学习与商业分析交叉。",
        47, "https://www.topuniversities.com/universities/chinese-university-hong-kong-cuhk",
        "HKD", 260000,
        "https://www.sci.cuhk.edu.hk/academic-programme/msc-in-data-science/",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.sci.cuhk.edu.hk/academic-programme/msc-in-data-science/",
        6.5, 79, "英语要求以 CUHK 官网为准。",
        ["https://www.sci.cuhk.edu.hk/academic-programme/msc-in-data-science/"],
        "STEM 或量化相关本科。",
        "https://www.sci.cuhk.edu.hk/academic-programme/msc-in-data-science/",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.sci.cuhk.edu.hk/academic-programme/msc-in-data-science/",
        "分轮次。",
        [{"name": "Round 1", "start": None, "end": "2026-01-31", "note": "参考"}],
        "https://www.sci.cuhk.edu.hk/academic-programme/msc-in-data-science/",
        "2026 entry",
        "https://www.sci.cuhk.edu.hk/academic-programme/msc-in-data-science/",
        "匹配", "high", False,
    ),
    base_program(
        "sg-ntu-msc-data-science",
        "Singapore", "Singapore", "Singapore",
        "Nanyang Technological University (NTU)", "南洋理工大学（NTU）",
        "MSc in Data Science", "数据科学理学硕士",
        ["DataScience"],
        "NTU 物理与数学科学学院数据科学 MSc，AI 与统计建模。",
        12, "https://www.topuniversities.com/universities/nanyang-technological-university-singapore-ntu",
        "SGD", 45000,
        "https://www.ntu.edu.sg/science/admissions/graduate-programmes/msc-data-science",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.ntu.edu.sg/science/admissions/graduate-programmes/msc-data-science",
        6.5, 90, "英语要求以 NTU 官网为准。",
        ["https://www.ntu.edu.sg/science/admissions/graduate-programmes/msc-data-science"],
        "量化或 STEM 背景。",
        "https://www.ntu.edu.sg/science/admissions/graduate-programmes/msc-data-science",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.ntu.edu.sg/science/admissions/graduate-programmes/msc-data-science",
        "分轮次。",
        [{"name": "Round 1", "start": None, "end": "2026-01-31", "note": "参考"}],
        "https://www.ntu.edu.sg/science/admissions/graduate-programmes/msc-data-science",
        "2026 entry",
        "https://www.ntu.edu.sg/science/admissions/graduate-programmes/msc-data-science",
        "匹配", "high", False,
    ),
    # ── Media ───────────────────────────────────────────────────
    base_program(
        "uk-kcl-ma-global-media",
        "UK", "United Kingdom", "London",
        "King's College London (KCL)", "伦敦国王学院（KCL）",
        "MA Global Media Industries", "全球媒体产业文学硕士",
        ["Media"],
        "KCL 文化、媒体与创意产业 MA，全球媒体产业与平台经济。",
        40, "https://www.topuniversities.com/universities/kings-college-london",
        "GBP", 29800,
        "https://www.kcl.ac.uk/study/postgraduate-taught/courses/global-media-industries-ma",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.kcl.ac.uk/study/postgraduate-taught/courses/global-media-industries-ma",
        7.0, 100, "英语要求以 KCL 官网为准。",
        ["https://www.kcl.ac.uk/study/postgraduate-taught/courses/global-media-industries-ma"],
        "2:1 人文社科或相关背景。",
        "https://www.kcl.ac.uk/study/postgraduate-taught/courses/global-media-industries-ma",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.kcl.ac.uk/study/postgraduate-taught/courses/global-media-industries-ma",
        "Rolling。",
        [{"name": "Rolling", "start": None, "end": None, "note": ""}],
        "https://www.kcl.ac.uk/study/postgraduate-taught/courses/global-media-industries-ma",
        "2026 entry / rolling",
        "https://www.kcl.ac.uk/study/postgraduate-taught/courses/global-media-industries-ma",
        "匹配", "high", False,
    ),
    base_program(
        "uk-goldsmiths-ma-media-communications",
        "UK", "United Kingdom", "London",
        "Goldsmiths, University of London", "伦敦大学金史密斯学院",
        "MA in Media and Communications", "媒体与传播文学硕士",
        ["Media"],
        "金史密斯传媒 MA，批判传播、数字文化与创意产业。",
        511, "https://www.topuniversities.com/universities/goldsmiths-university-london",
        "GBP", 22000,
        "https://www.gold.ac.uk/pg/ma-media-communications/",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.gold.ac.uk/pg/ma-media-communications/",
        6.5, 92, "英语要求以 Goldsmiths 官网为准。",
        ["https://www.gold.ac.uk/pg/ma-media-communications/"],
        "2:1 或相关背景；作品集部分方向需要。",
        "https://www.gold.ac.uk/pg/ma-media-communications/",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.gold.ac.uk/pg/ma-media-communications/",
        "Rolling。",
        [{"name": "Rolling", "start": None, "end": None, "note": ""}],
        "https://www.gold.ac.uk/pg/ma-media-communications/",
        "2026 entry / rolling",
        "https://www.gold.ac.uk/pg/ma-media-communications/",
        "匹配", "mid", False,
    ),
    base_program(
        "uk-leeds-ma-communication-media",
        "UK", "United Kingdom", "Leeds",
        "University of Leeds", "利兹大学",
        "MA Communication and Media", "传播与媒体文学硕士",
        ["Media"],
        "利兹传媒学院 MA，数字媒体、政治传播与文化产业。",
        82, "https://www.topuniversities.com/universities/university-leeds",
        "GBP", 25500,
        "https://courses.leeds.ac.uk/202526/8153/communication-and-media-ma",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://courses.leeds.ac.uk/202526/8153/communication-and-media-ma",
        6.5, 92, "英语要求以 Leeds 官网为准。",
        ["https://courses.leeds.ac.uk/202526/8153/communication-and-media-ma"],
        "2:1 人文社科或相关背景。",
        "https://courses.leeds.ac.uk/202526/8153/communication-and-media-ma",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://courses.leeds.ac.uk/202526/8153/communication-and-media-ma",
        "Rolling。",
        [{"name": "Rolling", "start": None, "end": None, "note": ""}],
        "https://courses.leeds.ac.uk/202526/8153/communication-and-media-ma",
        "2026 entry / rolling",
        "https://courses.leeds.ac.uk/202526/8153/communication-and-media-ma",
        "匹配", "mid", False,
    ),
    base_program(
        "uk-warwick-ma-global-media",
        "UK", "United Kingdom", "Coventry",
        "University of Warwick", "华威大学",
        "MA in Global Media and Communication", "全球媒体与传播文学硕士",
        ["Media"],
        "华威传媒 MA，全球化、跨文化传播与数字平台。",
        74, "https://www.topuniversities.com/universities/university-warwick",
        "GBP", 27650,
        "https://warwick.ac.uk/study/postgraduate/courses/ma-global-media-communication",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://warwick.ac.uk/study/postgraduate/courses/ma-global-media-communication",
        7.0, 100, "英语要求以 Warwick 官网为准。",
        ["https://warwick.ac.uk/study/postgraduate/courses/ma-global-media-communication"],
        "2:1 相关背景。",
        "https://warwick.ac.uk/study/postgraduate/courses/ma-global-media-communication",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://warwick.ac.uk/study/postgraduate/courses/ma-global-media-communication",
        "Rolling。",
        [{"name": "Rolling", "start": None, "end": None, "note": ""}],
        "https://warwick.ac.uk/study/postgraduate/courses/ma-global-media-communication",
        "2026 entry / rolling",
        "https://warwick.ac.uk/study/postgraduate/courses/ma-global-media-communication",
        "匹配", "mid", False,
    ),
    base_program(
        "uk-cardiff-ma-journalism",
        "UK", "United Kingdom", "Cardiff",
        "Cardiff University", "卡迪夫大学",
        "MA International Journalism", "国际新闻文学硕士",
        ["Media"],
        "卡迪夫新闻学院 MA，国际新闻与调查报道训练。",
        181, "https://www.topuniversities.com/universities/cardiff-university",
        "GBP", 22900,
        "https://www.cardiff.ac.uk/study/postgraduate/taught/courses/course/international-journalism-ma",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.cardiff.ac.uk/study/postgraduate/taught/courses/course/international-journalism-ma",
        7.0, 100, "英语要求以 Cardiff 官网为准。",
        ["https://www.cardiff.ac.uk/study/postgraduate/taught/courses/course/international-journalism-ma"],
        "2:1 或相关背景；新闻经历优先。",
        "https://www.cardiff.ac.uk/study/postgraduate/taught/courses/course/international-journalism-ma",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.cardiff.ac.uk/study/postgraduate/taught/courses/course/international-journalism-ma",
        "Rolling。",
        [{"name": "Rolling", "start": None, "end": None, "note": ""}],
        "https://www.cardiff.ac.uk/study/postgraduate/taught/courses/course/international-journalism-ma",
        "2026 entry / rolling",
        "https://www.cardiff.ac.uk/study/postgraduate/taught/courses/course/international-journalism-ma",
        "匹配", "mid", False,
    ),
    base_program(
        "us-columbia-ms-journalism",
        "US", "United States", "New York",
        "Columbia University", "哥伦比亚大学",
        "MS in Journalism", "新闻学理学硕士",
        ["Media"],
        "哥大新闻学院 MS，数据新闻、调查报道与多媒体叙事。",
        34, "https://www.topuniversities.com/universities/columbia-university",
        "USD", 78000,
        "https://journalism.columbia.edu/content/master-science",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://journalism.columbia.edu/content/master-science",
        7.0, 100, "英语要求以 Columbia Journalism 为准。",
        ["https://journalism.columbia.edu/content/master-science"],
        "本科任意背景；新闻作品集重要。",
        "https://journalism.columbia.edu/content/master-science",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://journalism.columbia.edu/content/master-science",
        "分轮次。",
        [{"name": "Round 1", "start": None, "end": "2026-01-15", "note": "参考"}],
        "https://journalism.columbia.edu/content/master-science",
        "2026 entry",
        "https://journalism.columbia.edu/content/master-science",
        "冲刺", "top", True,
    ),
    base_program(
        "us-nyu-ms-journalism",
        "US", "United States", "New York",
        "New York University (NYU)", "纽约大学（NYU）",
        "MA in Journalism", "新闻学文学硕士",
        ["Media"],
        "NYU Arthur L. Carter 新闻学院 MA，纽约媒体生态与数字新闻。",
        43, "https://www.topuniversities.com/universities/new-york-university-nyu",
        "USD", 72000,
        "https://journalism.nyu.edu/graduate/",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://journalism.nyu.edu/graduate/",
        7.0, 100, "英语要求以 NYU 官网为准。",
        ["https://journalism.nyu.edu/graduate/"],
        "本科任意背景；写作样本与经历重要。",
        "https://journalism.nyu.edu/graduate/",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://journalism.nyu.edu/graduate/",
        "分轮次。",
        [{"name": "Round 1", "start": None, "end": "2026-01-15", "note": "参考"}],
        "https://journalism.nyu.edu/graduate/",
        "2026 entry",
        "https://journalism.nyu.edu/graduate/",
        "冲刺", "top", True,
    ),
    base_program(
        "us-georgetown-ma-communication",
        "US", "United States", "Washington DC",
        "Georgetown University", "乔治城大学",
        "MA in Communication, Culture and Technology (CCT)", "传播、文化与技术 MA",
        ["Media"],
        "乔治城 CCT MA，数字文化、政策与新兴媒体技术。",
        301, "https://www.topuniversities.com/universities/georgetown-university",
        "USD", 62000,
        "https://cct.georgetown.edu/",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://cct.georgetown.edu/",
        7.0, 100, "英语要求以 Georgetown 官网为准。",
        ["https://cct.georgetown.edu/"],
        "本科任意背景；跨学科文书重要。",
        "https://cct.georgetown.edu/",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://cct.georgetown.edu/",
        "分轮次。",
        [{"name": "Round 1", "start": None, "end": "2026-01-15", "note": "参考"}],
        "https://cct.georgetown.edu/",
        "2026 entry",
        "https://cct.georgetown.edu/",
        "匹配", "high", False,
    ),
    base_program(
        "hk-hku-ma-media-culture-creative-cities",
        "HongKong", "Hong Kong SAR", "Hong Kong",
        "The University of Hong Kong (HKU)", "香港大学（HKU）",
        "MA in Media, Culture and Creative Cities", "媒体、文化与创意城市文学硕士",
        ["Media"],
        "港大社会学系 MA，媒体产业、城市文化与创意经济。",
        26, "https://www.topuniversities.com/universities/university-hong-kong",
        "HKD", 198000,
        "https://www.socsc.hku.hk/programmes/ma-media-culture-creative-cities",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.socsc.hku.hk/programmes/ma-media-culture-creative-cities",
        6.5, 80, "英语要求以 HKU 官网为准。",
        ["https://www.socsc.hku.hk/programmes/ma-media-culture-creative-cities"],
        "本科任意背景；人文社科优先。",
        "https://www.socsc.hku.hk/programmes/ma-media-culture-creative-cities",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.socsc.hku.hk/programmes/ma-media-culture-creative-cities",
        "分轮次。",
        [{"name": "Main Round", "start": None, "end": "2026-02-28", "note": "参考"}],
        "https://www.socsc.hku.hk/programmes/ma-media-culture-creative-cities",
        "2026 entry",
        "https://www.socsc.hku.hk/programmes/ma-media-culture-creative-cities",
        "冲刺", "top", True,
    ),
    base_program(
        "hk-polyu-ma-communication",
        "HongKong", "Hong Kong SAR", "Hong Kong",
        "The Hong Kong Polytechnic University (PolyU)", "香港理工大学",
        "MA in Communication and New Media", "传播与新媒体文学硕士",
        ["Media"],
        "理大传播学 MA，整合营销传播、新媒体与广告。",
        65, "https://www.topuniversities.com/universities/hong-kong-polytechnic-university",
        "HKD", 175000,
        "https://www.polyu.edu.hk/com/",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.polyu.edu.hk/com/",
        6.5, 79, "英语要求以 PolyU 官网为准。",
        ["https://www.polyu.edu.hk/com/"],
        "本科任意背景；传播相关经历优先。",
        "https://www.polyu.edu.hk/com/",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.polyu.edu.hk/com/",
        "分轮次。",
        [{"name": "Round 1", "start": None, "end": "2026-02-28", "note": "参考"}],
        "https://www.polyu.edu.hk/com/",
        "2026 entry",
        "https://www.polyu.edu.hk/com/",
        "匹配", "mid", False,
    ),
    base_program(
        "sg-nus-ma-communication",
        "Singapore", "Singapore", "Singapore",
        "National University of Singapore (NUS)", "新加坡国立大学（NUS）",
        "MA in Communications and New Media", "传播与新媒体文学硕士",
        ["Media"],
        "NUS 传播与新媒体 MA，数字平台、受众研究与亚洲媒体市场。",
        8, "https://www.topuniversities.com/universities/national-university-singapore-nus",
        "SGD", 42000,
        "https://fass.nus.edu.sg/cnm/graduate/ma/",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://fass.nus.edu.sg/cnm/graduate/ma/",
        6.5, 90, "英语要求以 NUS 官网为准。",
        ["https://fass.nus.edu.sg/cnm/graduate/ma/"],
        "本科任意背景。",
        "https://fass.nus.edu.sg/cnm/graduate/ma/",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://fass.nus.edu.sg/cnm/graduate/ma/",
        "分轮次。",
        [{"name": "Round 1", "start": None, "end": "2026-02-15", "note": "参考"}],
        "https://fass.nus.edu.sg/cnm/graduate/ma/",
        "2026 entry",
        "https://fass.nus.edu.sg/cnm/graduate/ma/",
        "冲刺", "top", True,
    ),
    # ── HCI ───────────────────────────────────────────────────────
    base_program(
        "uk-ucl-msc-hci",
        "UK", "United Kingdom", "London",
        "University College London (UCL)", "伦敦大学学院（UCL）",
        "MSc Human-Computer Interaction", "人机交互理学硕士",
        ["HCI"],
        "UCL 计算机系 HCI MSc，可用性、UX 研究与交互系统设计。",
        9, "https://www.topuniversities.com/universities/ucl",
        "GBP", 36500,
        "https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/human-computer-interaction-msc",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/human-computer-interaction-msc",
        7.0, 96, "英语要求以 UCL 官网为准。",
        ["https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/human-computer-interaction-msc"],
        "2:1 计算机、心理学、设计或相关背景。",
        "https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/human-computer-interaction-msc",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/human-computer-interaction-msc",
        "Rolling。",
        [{"name": "Rolling", "start": None, "end": None, "note": ""}],
        "https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/human-computer-interaction-msc",
        "2026 entry / rolling",
        "https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/human-computer-interaction-msc",
        "冲刺", "top", True,
    ),
    base_program(
        "uk-goldsmiths-ma-interaction-design",
        "UK", "United Kingdom", "London",
        "Goldsmiths, University of London", "伦敦大学金史密斯学院",
        "MA in Interaction Design", "交互设计文学硕士",
        ["HCI"],
        "金史密斯交互设计 MA，服务设计、原型与数字产品体验。",
        511, "https://www.topuniversities.com/universities/goldsmiths-university-london",
        "GBP", 24000,
        "https://www.gold.ac.uk/pg/ma-interaction-design/",
        "学费以官网为准。",
        15, "months", "Full-time",
        "https://www.gold.ac.uk/pg/ma-interaction-design/",
        6.5, 92, "英语要求以 Goldsmiths 官网为准。",
        ["https://www.gold.ac.uk/pg/ma-interaction-design/"],
        "设计/艺术/技术相关背景；作品集通常需要。",
        "https://www.gold.ac.uk/pg/ma-interaction-design/",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.gold.ac.uk/pg/ma-interaction-design/",
        "Rolling。",
        [{"name": "Rolling", "start": None, "end": None, "note": ""}],
        "https://www.gold.ac.uk/pg/ma-interaction-design/",
        "2026 entry / rolling",
        "https://www.gold.ac.uk/pg/ma-interaction-design/",
        "匹配", "mid", False,
    ),
    base_program(
        "uk-loughborough-msc-ux-design",
        "UK", "United Kingdom", "Loughborough",
        "Loughborough University", "拉夫堡大学",
        "MSc User Experience Design", "用户体验设计理学硕士",
        ["HCI"],
        "拉夫堡设计学院 UX MSc，用户研究、原型与可用性测试。",
        224, "https://www.topuniversities.com/universities/loughborough-university",
        "GBP", 25500,
        "https://www.lboro.ac.uk/study/postgraduate/masters-degrees/a-z/user-experience-design/",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.lboro.ac.uk/study/postgraduate/masters-degrees/a-z/user-experience-design/",
        6.5, 92, "英语要求以 Loughborough 官网为准。",
        ["https://www.lboro.ac.uk/study/postgraduate/masters-degrees/a-z/user-experience-design/"],
        "2:1 设计、心理学、CS 或相关背景。",
        "https://www.lboro.ac.uk/study/postgraduate/masters-degrees/a-z/user-experience-design/",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.lboro.ac.uk/study/postgraduate/masters-degrees/a-z/user-experience-design/",
        "Rolling。",
        [{"name": "Rolling", "start": None, "end": None, "note": ""}],
        "https://www.lboro.ac.uk/study/postgraduate/masters-degrees/a-z/user-experience-design/",
        "2026 entry / rolling",
        "https://www.lboro.ac.uk/study/postgraduate/masters-degrees/a-z/user-experience-design/",
        "匹配", "mid", False,
    ),
    base_program(
        "us-cmu-mhci",
        "US", "United States", "Pittsburgh",
        "Carnegie Mellon University (CMU)", "卡内基梅隆大学（CMU）",
        "Master of Human-Computer Interaction (MHCI)", "人机交互硕士（MHCI）",
        ["HCI"],
        "CMU HCII MHCI，业界标杆 UX/HCI 项目，含 capstone 与企业合作。",
        52, "https://www.topuniversities.com/universities/carnegie-mellon-university",
        "USD", 58000,
        "https://www.hcii.cmu.edu/academics/mhci",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.hcii.cmu.edu/academics/mhci",
        7.0, 100, "英语要求以 CMU 官网为准。",
        ["https://www.hcii.cmu.edu/academics/mhci"],
        "本科任意背景；作品集与文书重要。",
        "https://www.hcii.cmu.edu/academics/mhci",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.hcii.cmu.edu/academics/mhci",
        "分轮次。",
        [{"name": "Round 1", "start": None, "end": "2025-12-15", "note": "参考"}],
        "https://www.hcii.cmu.edu/academics/mhci",
        "2026 entry",
        "https://www.hcii.cmu.edu/academics/mhci",
        "冲刺", "top", True,
    ),
    base_program(
        "us-gatech-ms-hci",
        "US", "United States", "Atlanta",
        "Georgia Institute of Technology", "佐治亚理工学院（Georgia Tech）",
        "MS in Human-Computer Interaction", "人机交互理学硕士",
        ["HCI"],
        "Georgia Tech MS-HCI，跨学院（CS/设计/心理学/工业工程）联合培养。",
        114, "https://www.topuniversities.com/universities/georgia-institute-technology",
        "USD", 42000,
        "https://www.mshci.gatech.edu/",
        "学费以官网为准。",
        24, "months", "Full-time",
        "https://www.mshci.gatech.edu/",
        7.0, 100, "英语要求以 Georgia Tech 官网为准。",
        ["https://www.mshci.gatech.edu/"],
        "本科任意背景；作品集与文书重要。",
        "https://www.mshci.gatech.edu/",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.mshci.gatech.edu/",
        "分轮次。",
        [{"name": "Round 1", "start": None, "end": "2026-02-01", "note": "参考"}],
        "https://www.mshci.gatech.edu/",
        "2026 entry",
        "https://www.mshci.gatech.edu/",
        "冲刺", "top", True,
    ),
    base_program(
        "us-uw-ms-hcde",
        "US", "United States", "Seattle",
        "University of Washington", "华盛顿大学",
        "MS in Human Centered Design and Engineering (HCDE)", "以人为中心的设计与工程硕士",
        ["HCI"],
        "UW HCDE MS，UX 研究、交互设计与科技产品伦理。",
        76, "https://www.topuniversities.com/universities/university-washington",
        "USD", 48000,
        "https://hcde.uw.edu/academics/graduate/masters",
        "学费以官网为准。",
        18, "months", "Full-time",
        "https://hcde.uw.edu/academics/graduate/masters",
        7.0, 100, "英语要求以 UW 官网为准。",
        ["https://hcde.uw.edu/academics/graduate/masters"],
        "本科任意背景；技术或设计经历优先。",
        "https://hcde.uw.edu/academics/graduate/masters",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://hcde.uw.edu/academics/graduate/masters",
        "分轮次。",
        [{"name": "Round 1", "start": None, "end": "2026-01-15", "note": "参考"}],
        "https://hcde.uw.edu/academics/graduate/masters",
        "2026 entry",
        "https://hcde.uw.edu/academics/graduate/masters",
        "匹配", "high", False,
    ),
    base_program(
        "us-umich-msi",
        "US", "United States", "Ann Arbor",
        "University of Michigan", "密歇根大学",
        "Master of Science in Information (MSI) — HCI Specialization", "信息学硕士（HCI 方向）",
        ["HCI"],
        "密歇根信息学院 MSI，人机交互、UX 与信息架构方向。",
        33, "https://www.topuniversities.com/universities/university-michigan",
        "USD", 56000,
        "https://www.si.umich.edu/programs/masters-degrees",
        "学费以官网为准。",
        24, "months", "Full-time",
        "https://www.si.umich.edu/programs/masters-degrees",
        7.0, 100, "英语要求以 Michigan 官网为准。",
        ["https://www.si.umich.edu/programs/masters-degrees"],
        "本科任意背景；文书与经历重要。",
        "https://www.si.umich.edu/programs/masters-degrees",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.si.umich.edu/programs/masters-degrees",
        "分轮次。",
        [{"name": "Round 1", "start": None, "end": "2026-01-15", "note": "参考"}],
        "https://www.si.umich.edu/programs/masters-degrees",
        "2026 entry",
        "https://www.si.umich.edu/programs/masters-degrees",
        "冲刺", "top", True,
    ),
    base_program(
        "hk-polyu-msc-ux",
        "HongKong", "Hong Kong SAR", "Hong Kong",
        "The Hong Kong Polytechnic University (PolyU)", "香港理工大学",
        "MSc in Multimedia and Entertainment Technology (Interaction Design stream)", "多媒体与娱乐科技硕士（交互方向）",
        ["HCI"],
        "理大设计学院 MET MSc，游戏、交互与数字体验设计。",
        65, "https://www.topuniversities.com/universities/hong-kong-polytechnic-university",
        "HKD", 168000,
        "https://www.polyu.edu.hk/sd/",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.polyu.edu.hk/sd/",
        6.5, 79, "英语要求以 PolyU 官网为准。",
        ["https://www.polyu.edu.hk/sd/"],
        "设计/工程/媒体相关背景；作品集通常需要。",
        "https://www.polyu.edu.hk/sd/",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.polyu.edu.hk/sd/",
        "分轮次。",
        [{"name": "Round 1", "start": None, "end": "2026-02-28", "note": "参考"}],
        "https://www.polyu.edu.hk/sd/",
        "2026 entry",
        "https://www.polyu.edu.hk/sd/",
        "匹配", "mid", False,
    ),
    base_program(
        "sg-ntu-ma-design",
        "Singapore", "Singapore", "Singapore",
        "Nanyang Technological University (NTU)", "南洋理工大学（NTU）",
        "MA in Design (Interaction Design)", "设计文学硕士（交互设计）",
        ["HCI"],
        "NTU 艺术设计学院 MA Design，交互、服务与体验设计。",
        12, "https://www.topuniversities.com/universities/nanyang-technological-university-singapore-ntu",
        "SGD", 38000,
        "https://www.ntu.edu.sg/adm/graduate-studies/programmes",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.ntu.edu.sg/adm/graduate-studies/programmes",
        6.5, 90, "英语要求以 NTU 官网为准。",
        ["https://www.ntu.edu.sg/adm/graduate-studies/programmes"],
        "设计或相关背景；作品集重要。",
        "https://www.ntu.edu.sg/adm/graduate-studies/programmes",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.ntu.edu.sg/adm/graduate-studies/programmes",
        "分轮次。",
        [{"name": "Round 1", "start": None, "end": "2026-01-31", "note": "参考"}],
        "https://www.ntu.edu.sg/adm/graduate-studies/programmes",
        "2026 entry",
        "https://www.ntu.edu.sg/adm/graduate-studies/programmes",
        "匹配", "mid", False,
    ),
]


def main():
    data = json.loads(DATA_PATH.read_text(encoding="utf-8"))
    existing_ids = {p["id"] for p in data["programs"]}
    added = []
    skipped = []
    for program in NEW_PROGRAMS:
        if program["id"] in existing_ids:
            skipped.append(program["id"])
            continue
        data["programs"].append(program)
        existing_ids.add(program["id"])
        added.append(program["id"])

    for program in data["programs"]:
        if program.get("id") == "us-gatech-ms-cs":
            tags = program.get("program", {}).get("tags") or []
            if "HCI" in tags:
                program["program"]["tags"] = [t for t in tags if t != "HCI"]

    retagged = 0
    for program in data["programs"]:
        before = list(program.get("program", {}).get("tags") or [])
        merge_inferred_tags(program)
        after = list(program.get("program", {}).get("tags") or [])
        if after != before:
            retagged += 1

    data["meta"]["last_built_at"] = VERIFIED
    data["meta"]["scope_note"] = (
        f"共 {len(data['programs'])} 个项目；覆盖商科、计算机、传媒、数据科学、交互设计、法律、教育等；"
        "UK/US/HK/SG；官网公开字段 + 经验性评估。"
    )

    DATA_PATH.write_text(
        json.dumps(data, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(f"Added {len(added)} programs (skipped {len(skipped)} duplicates)")
    print(f"Retagged {retagged} programs")
    print(f"Total programs: {len(data['programs'])}")
    if skipped:
        print("Skipped:", skipped)


if __name__ == "__main__":
    main()
