#!/usr/bin/env python3
"""Add CS / Media / Data Science programs and refresh meta."""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(Path(__file__).resolve().parent))
from add_programs_batch import base_program, VERIFIED  # noqa: E402

DATA_PATH = ROOT / "data" / "programs.json"

NEW_PROGRAMS = [
    # UK — CS / Data / Media / HCI
    base_program(
        "uk-imperial-msc-computing",
        "UK", "United Kingdom", "London",
        "Imperial College London", "帝国理工学院",
        "MSc Computing (Artificial Intelligence)", "计算机硕士（人工智能方向）",
        ["CS", "DataScience"],
        "帝国理工计算机系 AI 方向硕士，强调机器学习与深度学习。",
        2, "https://www.topuniversities.com/universities/imperial-college-london",
        "GBP", 42500,
        "https://www.imperial.ac.uk/study/courses/postgraduate-taught/computing-artificial-intelligence/",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.imperial.ac.uk/study/courses/postgraduate-taught/computing-artificial-intelligence/",
        7.0, 100, "英语要求以 Imperial 研究生英语页为准。",
        ["https://www.imperial.ac.uk/study/courses/postgraduate-taught/computing-artificial-intelligence/"],
        "通常要求一等或 2:1 相关 STEM 本科学位。",
        "https://www.imperial.ac.uk/study/courses/postgraduate-taught/computing-artificial-intelligence/",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.imperial.ac.uk/study/courses/postgraduate-taught/computing-artificial-intelligence/",
        "分轮次；国际生建议尽早。",
        [{"name": "Round 1", "start": None, "end": "2026-01-15", "note": "以官网为准"}],
        "https://www.imperial.ac.uk/study/courses/postgraduate-taught/computing-artificial-intelligence/",
        "2026 entry",
        "https://www.imperial.ac.uk/study/courses/postgraduate-taught/computing-artificial-intelligence/",
        "冲刺", "top", True,
    ),
    base_program(
        "uk-ucl-msc-data-science",
        "UK", "United Kingdom", "London",
        "University College London (UCL)", "伦敦大学学院（UCL）",
        "MSc Data Science", "数据科学硕士（MSc Data Science）",
        ["DataScience", "CS"],
        "UCL 数据科学硕士，统计、机器学习与大规模数据分析。",
        9, "https://www.topuniversities.com/universities/ucl",
        "GBP", 36500,
        "https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/data-science-msc",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/data-science-msc",
        7.0, 96, "英语要求以 UCL 官网为准。",
        ["https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/data-science-msc"],
        "2:1 量化或计算相关背景。",
        "https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/data-science-msc",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/data-science-msc",
        "Rolling；建议尽早。",
        [{"name": "Rolling", "start": None, "end": None, "note": "招满即止"}],
        "https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/data-science-msc",
        "2026 entry / rolling",
        "https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/data-science-msc",
        "冲刺", "top", True,
    ),
    base_program(
        "uk-lse-msc-media-communications",
        "UK", "United Kingdom", "London",
        "The London School of Economics and Political Science (LSE)", "伦敦政治经济学院（LSE）",
        "MSc Media and Communications", "媒体与传播硕士",
        ["Media"],
        "LSE 媒体与传播硕士，偏政治经济、数字平台与全球传播。",
        56, "https://www.topuniversities.com/universities/london-school-economics-political-science-lse",
        "GBP", 28900,
        "https://www.lse.ac.uk/study-at-lse/graduate/msc-media-and-communications",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.lse.ac.uk/study-at-lse/graduate/msc-media-and-communications",
        7.0, 100, "Standard profile 英语要求。",
        ["https://www.lse.ac.uk/study-at-lse/graduate/msc-media-and-communications"],
        "2:1 社会科学或相关背景。",
        "https://www.lse.ac.uk/study-at-lse/graduate/msc-media-and-communications",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.lse.ac.uk/study-at-lse/graduate/msc-media-and-communications",
        "Rolling admissions。",
        [{"name": "Rolling", "start": None, "end": None, "note": ""}],
        "https://www.lse.ac.uk/study-at-lse/graduate/msc-media-and-communications",
        "2026 entry / rolling",
        "https://www.lse.ac.uk/study-at-lse/graduate/msc-media-and-communications",
        "冲刺", "high", True,
    ),
    base_program(
        "uk-edinburgh-msc-design-informatics",
        "UK", "United Kingdom", "Edinburgh",
        "The University of Edinburgh", "爱丁堡大学",
        "MSc Design Informatics", "设计信息学硕士",
        ["HCI", "CS"],
        "爱丁堡设计与信息学交叉硕士，产品、数据与交互设计。",
        34, "https://www.topuniversities.com/universities/university-edinburgh",
        "GBP", 40300,
        "https://www.ed.ac.uk/studying/postgraduate/degrees/index.php?r=site/view&id=900",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.ed.ac.uk/studying/postgraduate/degrees/index.php?r=site/view&id=900",
        7.0, 100, "英语要求以官网为准。",
        ["https://www.ed.ac.uk/studying/postgraduate/degrees/index.php?r=site/view&id=900"],
        "2:1 或同等；欢迎设计/计算机/工程背景。",
        "https://www.ed.ac.uk/studying/postgraduate/degrees/index.php?r=site/view&id=900",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.ed.ac.uk/studying/postgraduate/degrees/index.php?r=site/view&id=900",
        "分轮次录取。",
        [{"name": "Round 3", "start": None, "end": "2026-05-14", "note": "国际生参考"}],
        "https://www.ed.ac.uk/studying/postgraduate/degrees/index.php?r=site/view&id=900",
        "2026 entry",
        "https://www.ed.ac.uk/studying/postgraduate/degrees/index.php?r=site/view&id=900",
        "匹配", "high", False,
    ),
    base_program(
        "uk-warwick-msc-cs",
        "UK", "United Kingdom", "Coventry",
        "University of Warwick", "华威大学",
        "MSc Computer Science", "计算机科学硕士",
        ["CS"],
        "华威计算机科学硕士，含软件、系统与 AI 选修。",
        74, "https://www.topuniversities.com/universities/university-warwick",
        "GBP", 35340,
        "https://warwick.ac.uk/study/postgraduate/courses/msc-computer-science",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://warwick.ac.uk/study/postgraduate/courses/msc-computer-science",
        6.5, 92, "英语要求以 Warwick 官网为准。",
        ["https://warwick.ac.uk/study/postgraduate/courses/msc-computer-science"],
        "2:1 计算机或强相关 STEM 背景。",
        "https://warwick.ac.uk/study/postgraduate/courses/msc-computer-science",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://warwick.ac.uk/study/postgraduate/courses/msc-computer-science",
        "建议尽早申请。",
        [{"name": "Rolling", "start": None, "end": "2026-08-31", "note": ""}],
        "https://warwick.ac.uk/study/postgraduate/courses/msc-computer-science",
        "2026 entry",
        "https://warwick.ac.uk/study/postgraduate/courses/msc-computer-science",
        "匹配", "mid", False,
    ),
    # US — CS / Data / Media
    base_program(
        "us-cmu-mscs",
        "US", "United States", "Pittsburgh",
        "Carnegie Mellon University", "卡内基梅隆大学（CMU）",
        "Master of Science in Computer Science (MSCS)", "计算机科学硕士（MSCS）",
        ["CS"],
        "CMU 计算机学院旗舰 MSCS，偏系统、AI 与软件工程。",
        52, "https://www.topuniversities.com/universities/carnegie-mellon-university",
        "USD", 54000,
        "https://www.cs.cmu.edu/academics/masters/programs.html",
        "学费以官网为准，不含生活费。",
        16, "months", "Full-time",
        "https://www.cs.cmu.edu/academics/masters/programs.html",
        7.0, 100, "TOEFL/IELTS 以 CMU 研究生院为准。",
        ["https://www.cs.cmu.edu/academics/masters/programs.html"],
        "强 STEM 本科；需较强编程与数学背景。",
        "https://www.cs.cmu.edu/academics/masters/programs.html",
        "数据缺失", "数据缺失", "GRE 政策以当年官网为准。",
        "https://www.cs.cmu.edu/academics/masters/programs.html",
        "分轮次；截止以官网为准。",
        [{"name": "Fall", "start": None, "end": "2025-12-15", "note": "参考往年"}],
        "https://www.cs.cmu.edu/academics/masters/programs.html",
        "2026 entry",
        "https://www.cs.cmu.edu/academics/masters/programs.html",
        "冲刺", "top", True,
    ),
    base_program(
        "us-nyu-ms-data-science",
        "US", "United States", "New York",
        "New York University (NYU)", "纽约大学（NYU）",
        "MS in Data Science", "数据科学硕士（MS Data Science）",
        ["DataScience", "CS"],
        "NYU CDS 数据科学硕士，机器学习、统计与大规模计算。",
        43, "https://www.topuniversities.com/universities/new-york-university-nyu",
        "USD", 62000,
        "https://cds.nyu.edu/admissions/ms-in-data-science-admissions/",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://cds.nyu.edu/admissions/ms-in-data-science-admissions/",
        7.0, 100, "英语要求以 NYU 研究生院为准。",
        ["https://cds.nyu.edu/admissions/ms-in-data-science-admissions/"],
        "量化、计算机或统计相关本科。",
        "https://cds.nyu.edu/admissions/ms-in-data-science-admissions/",
        "数据缺失", "数据缺失", "GRE 可选/以官网为准。",
        "https://cds.nyu.edu/admissions/ms-in-data-science-admissions/",
        "分轮次。",
        [{"name": "Priority", "start": None, "end": "2026-02-15", "note": "参考"}],
        "https://cds.nyu.edu/admissions/ms-in-data-science-admissions/",
        "2026 entry",
        "https://cds.nyu.edu/admissions/ms-in-data-science-admissions/",
        "冲刺", "top", True,
    ),
    base_program(
        "us-usc-ma-communication-management",
        "US", "United States", "Los Angeles",
        "University of Southern California (USC)", "南加州大学（USC）",
        "MA in Communication Management", "传播管理硕士（MA）",
        ["Media", "MKT"],
        "USC Annenberg 传播管理硕士，品牌传播、数字媒体与战略沟通。",
        116, "https://www.topuniversities.com/universities/university-southern-california",
        "USD", 65000,
        "https://annenberg.usc.edu/academics/graduate-communication/communication-management",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://annenberg.usc.edu/academics/graduate-communication/communication-management",
        7.0, 100, "英语要求以 USC 研究生院为准。",
        ["https://annenberg.usc.edu/academics/graduate-communication/communication-management"],
        "本科任意背景；需文书与相关经历。",
        "https://annenberg.usc.edu/academics/graduate-communication/communication-management",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://annenberg.usc.edu/academics/graduate-communication/communication-management",
        "分轮次。",
        [{"name": "Round 1", "start": None, "end": "2025-12-01", "note": "参考"}],
        "https://annenberg.usc.edu/academics/graduate-communication/communication-management",
        "2026 entry",
        "https://annenberg.usc.edu/academics/graduate-communication/communication-management",
        "匹配", "high", False,
    ),
    base_program(
        "us-gatech-ms-cs",
        "US", "United States", "Atlanta",
        "Georgia Institute of Technology", "佐治亚理工学院",
        "MS in Computer Science", "计算机科学硕士",
        ["CS"],
        "Georgia Tech 计算机硕士，含机器学习、系统、人机交互等方向。",
        114, "https://www.topuniversities.com/universities/georgia-institute-technology",
        "USD", 32000,
        "https://www.cc.gatech.edu/degree-programs/computer-science",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.cc.gatech.edu/degree-programs/computer-science",
        7.0, 100, "英语要求以 Georgia Tech 官网为准。",
        ["https://www.cc.gatech.edu/degree-programs/computer-science"],
        "计算机或强相关 STEM 本科。",
        "https://www.cc.gatech.edu/degree-programs/computer-science",
        "数据缺失", "数据缺失", "GRE 以官网为准。",
        "https://www.cc.gatech.edu/degree-programs/computer-science",
        "分轮次。",
        [{"name": "Fall", "start": None, "end": "2026-02-01", "note": "参考"}],
        "https://www.cc.gatech.edu/degree-programs/computer-science",
        "2026 entry",
        "https://www.cc.gatech.edu/degree-programs/computer-science",
        "匹配", "high", False,
    ),
    base_program(
        "us-northwestern-msj",
        "US", "United States", "Evanston",
        "Northwestern University", "西北大学",
        "MS in Journalism", "新闻学硕士（MSJ）",
        ["Media"],
        "Medill 新闻学硕士，调查报道、数字新闻与多媒体叙事。",
        32, "https://www.topuniversities.com/universities/northwestern-university",
        "USD", 72000,
        "https://www.medill.northwestern.edu/journalism/graduate/masters-program/",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.medill.northwestern.edu/journalism/graduate/masters-program/",
        7.0, 100, "英语要求以 Northwestern 官网为准。",
        ["https://www.medill.northwestern.edu/journalism/graduate/masters-program/"],
        "本科任意背景；看重写作样本。",
        "https://www.medill.northwestern.edu/journalism/graduate/masters-program/",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.medill.northwestern.edu/journalism/graduate/masters-program/",
        "分轮次。",
        [{"name": "Round 1", "start": None, "end": "2025-11-15", "note": "参考"}],
        "https://www.medill.northwestern.edu/journalism/graduate/masters-program/",
        "2026 entry",
        "https://www.medill.northwestern.edu/journalism/graduate/masters-program/",
        "冲刺", "top", True,
    ),
    # Hong Kong
    base_program(
        "hk-hku-msc-cs",
        "HongKong", "Hong Kong SAR", "Hong Kong",
        "The University of Hong Kong (HKU)", "香港大学（HKU）",
        "MSc in Computer Science", "计算机科学硕士",
        ["CS"],
        "港大计算机科学硕士，含网络安全、金融计算、AI 等 stream。",
        26, "https://www.topuniversities.com/universities/university-hong-kong",
        "HKD", 320000,
        "https://www.cs.hku.hk/index.php/programmes/msc-cs",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.cs.hku.hk/index.php/programmes/msc-cs",
        6.5, 80, "英语要求以 HKU 研究生院为准。",
        ["https://www.cs.hku.hk/index.php/programmes/msc-cs"],
        "相关 STEM 或计算机本科。",
        "https://www.cs.hku.hk/index.php/programmes/msc-cs",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.cs.hku.hk/index.php/programmes/msc-cs",
        "主轮次截止以官网为准。",
        [{"name": "Main Round", "start": None, "end": "2026-02-28", "note": "参考"}],
        "https://www.cs.hku.hk/index.php/programmes/msc-cs",
        "2026 entry",
        "https://www.cs.hku.hk/index.php/programmes/msc-cs",
        "冲刺", "top", True,
    ),
    base_program(
        "hk-cuhk-msc-journalism",
        "HongKong", "Hong Kong SAR", "Hong Kong",
        "The Chinese University of Hong Kong (CUHK)", "香港中文大学（CUHK）",
        "MA in Journalism", "新闻学文学硕士",
        ["Media"],
        "中大新闻与传播学院新闻学硕士，财经/商业/国际报道等方向。",
        47, "https://www.topuniversities.com/universities/chinese-university-hong-kong-cuhk",
        "HKD", 180000,
        "https://www.com.cuhk.edu.hk/programmes/ma-in-journalism/",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.com.cuhk.edu.hk/programmes/ma-in-journalism/",
        6.5, 79, "英语要求以 CUHK 研究生院为准。",
        ["https://www.com.cuhk.edu.hk/programmes/ma-in-journalism/"],
        "本科任意背景；需新闻或相关经历。",
        "https://www.com.cuhk.edu.hk/programmes/ma-in-journalism/",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.com.cuhk.edu.hk/programmes/ma-in-journalism/",
        "分轮次。",
        [{"name": "Round 1", "start": None, "end": "2026-01-15", "note": "参考"}],
        "https://www.com.cuhk.edu.hk/programmes/ma-in-journalism/",
        "2026 entry",
        "https://www.com.cuhk.edu.hk/programmes/ma-in-journalism/",
        "匹配", "high", False,
    ),
    base_program(
        "hk-hkust-msc-big-data",
        "HongKong", "Hong Kong SAR", "Hong Kong",
        "The Hong Kong University of Science and Technology (HKUST)", "香港科技大学（HKUST）",
        "MSc in Big Data Technology", "大数据科技硕士",
        ["DataScience", "CS"],
        "港科大大数据科技硕士，数据挖掘、机器学习与分布式系统。",
        44, "https://www.topuniversities.com/universities/hong-kong-university-science-technology",
        "HKD", 350000,
        "https://www.cse.ust.hk/acad_prog/pg/msc_bdt/",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.cse.ust.hk/acad_prog/pg/msc_bdt/",
        6.5, 80, "英语要求以 HKUST 研究生院为准。",
        ["https://www.cse.ust.hk/acad_prog/pg/msc_bdt/"],
        "计算机、工程或相关量化背景。",
        "https://www.cse.ust.hk/acad_prog/pg/msc_bdt/",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.cse.ust.hk/acad_prog/pg/msc_bdt/",
        "分轮次。",
        [{"name": "Round 1", "start": None, "end": "2026-02-01", "note": "参考"}],
        "https://www.cse.ust.hk/acad_prog/pg/msc_bdt/",
        "2026 entry",
        "https://www.cse.ust.hk/acad_prog/pg/msc_bdt/",
        "冲刺", "top", True,
    ),
    base_program(
        "hk-cityu-ma-communication",
        "HongKong", "Hong Kong SAR", "Hong Kong",
        "City University of Hong Kong", "香港城市大学",
        "MA in Communication and New Media", "传播与新媒体文学硕士",
        ["Media"],
        "城大创意媒体学院传播与新媒体硕士，数字媒体与创意传播。",
        62, "https://www.topuniversities.com/universities/city-university-hong-kong",
        "HKD", 198000,
        "https://www.cityu.edu.hk/ma-com/",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.cityu.edu.hk/ma-com/",
        6.5, 79, "英语要求以 CityU 官网为准。",
        ["https://www.cityu.edu.hk/ma-com/"],
        "本科任意背景。",
        "https://www.cityu.edu.hk/ma-com/",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.cityu.edu.hk/ma-com/",
        "分轮次。",
        [{"name": "Round 1", "start": None, "end": "2026-02-28", "note": "参考"}],
        "https://www.cityu.edu.hk/ma-com/",
        "2026 entry",
        "https://www.cityu.edu.hk/ma-com/",
        "匹配", "mid", False,
    ),
    # Singapore
    base_program(
        "sg-nus-msc-cs",
        "Singapore", "Singapore", "Singapore",
        "National University of Singapore (NUS)", "新加坡国立大学（NUS）",
        "MSc in Computer Science", "计算机科学硕士",
        ["CS"],
        "NUS 计算机科学硕士，含 AI、计算机系统、信息安全等 specialization。",
        8, "https://www.topuniversities.com/universities/national-university-singapore-nus",
        "SGD", 55000,
        "https://www.comp.nus.edu.sg/programmes/pg/mcs/",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.comp.nus.edu.sg/programmes/pg/mcs/",
        6.5, 90, "英语要求以 NUS 研究生院为准。",
        ["https://www.comp.nus.edu.sg/programmes/pg/mcs/"],
        "计算机或强相关本科。",
        "https://www.comp.nus.edu.sg/programmes/pg/mcs/",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.comp.nus.edu.sg/programmes/pg/mcs/",
        "分轮次。",
        [{"name": "Round 1", "start": None, "end": "2026-02-15", "note": "参考"}],
        "https://www.comp.nus.edu.sg/programmes/pg/mcs/",
        "2026 entry",
        "https://www.comp.nus.edu.sg/programmes/pg/mcs/",
        "冲刺", "top", True,
    ),
    base_program(
        "sg-ntu-wkwsci-ma-communication",
        "Singapore", "Singapore", "Singapore",
        "Nanyang Technological University (NTU)", "南洋理工大学（NTU）",
        "MA in Communication Studies", "传播学文学硕士",
        ["Media"],
        "NTU 黄金辉传播学院传播学硕士，战略传播、媒体研究。",
        12, "https://www.topuniversities.com/universities/nanyang-technological-university-singapore-ntu",
        "SGD", 42000,
        "https://www.ntu.edu.sg/education/graduate-programme/master-of-arts-in-communication-studies",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://www.ntu.edu.sg/education/graduate-programme/master-of-arts-in-communication-studies",
        6.5, 90, "英语要求以 NTU 官网为准。",
        ["https://www.ntu.edu.sg/education/graduate-programme/master-of-arts-in-communication-studies"],
        "本科任意背景。",
        "https://www.ntu.edu.sg/education/graduate-programme/master-of-arts-in-communication-studies",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://www.ntu.edu.sg/education/graduate-programme/master-of-arts-in-communication-studies",
        "分轮次。",
        [{"name": "Round 1", "start": None, "end": "2026-01-31", "note": "参考"}],
        "https://www.ntu.edu.sg/education/graduate-programme/master-of-arts-in-communication-studies",
        "2026 entry",
        "https://www.ntu.edu.sg/education/graduate-programme/master-of-arts-in-communication-studies",
        "匹配", "high", False,
    ),
    base_program(
        "sg-smu-msc-computing",
        "Singapore", "Singapore", "Singapore",
        "Singapore Management University (SMU)", "新加坡管理大学（SMU）",
        "MSc in Computing", "计算硕士",
        ["CS", "DataScience"],
        "SMU 计算硕士，软件、AI 与信息系统方向。",
        511, "https://www.topuniversities.com/universities/singapore-management-university",
        "SGD", 52000,
        "https://masters.smu.edu.sg/programme/master-of-science-in-computing",
        "学费以官网为准。",
        12, "months", "Full-time",
        "https://masters.smu.edu.sg/programme/master-of-science-in-computing",
        6.5, 90, "英语要求以 SMU 官网为准。",
        ["https://masters.smu.edu.sg/programme/master-of-science-in-computing"],
        "计算机或相关本科。",
        "https://masters.smu.edu.sg/programme/master-of-science-in-computing",
        "数据缺失", "数据缺失", "未强制 GRE/GMAT。",
        "https://masters.smu.edu.sg/programme/master-of-science-in-computing",
        "分轮次。",
        [{"name": "Round 1", "start": None, "end": "2026-02-15", "note": "参考"}],
        "https://masters.smu.edu.sg/programme/master-of-science-in-computing",
        "2026 entry",
        "https://masters.smu.edu.sg/programme/master-of-science-in-computing",
        "匹配", "mid", False,
    ),
]


def merge_inferred_tags(program: dict) -> None:
    """Persist keyword-inferred tags alongside explicit tags in JSON."""
    explicit = list(program.get("program", {}).get("tags") or [])
    text = " ".join(
        filter(
            None,
            [
                program.get("program", {}).get("name_en"),
                program.get("program", {}).get("name_zh"),
                program.get("program", {}).get("summary_zh"),
            ],
        )
    ).lower()
    rules = [
        ("BA", ["business analytics", "msba", "mban", "商业分析"]),
        ("Finance", ["finance", "mfin", "financial", "金融"]),
        ("MKT", ["marketing", "mkt", "market", "市场"]),
        ("Management", ["management", "strategy", "管理", "mba"]),
        ("Economics", ["economics", "econ", "经济"]),
        ("MIS", ["information systems", "mis", "mism", "信息系统"]),
        ("CS", ["computer science", "computing", "software engineering", "计算机", "artificial intelligence", "machine learning"]),
        ("DataScience", ["data science", "big data", "数据科学", "大数据"]),
        ("Media", ["media", "communication", "journalism", "传播", "新闻", "传媒"]),
        ("HCI", ["human-computer", "interaction design", "design informatics", "交互"]),
        ("Law", ["law", "legal", "llm", "法学", "法律"]),
        ("Education", ["education", "teaching", "pedagogy", "tesol", "教育", "教育学"]),
    ]
    inferred = [tag for tag, keywords in rules if any(kw in text for kw in keywords)]
    merged = list(dict.fromkeys([*explicit, *inferred]))
    program.setdefault("program", {})["tags"] = merged


def main():
    data = json.loads(DATA_PATH.read_text(encoding="utf-8"))
    existing_ids = {p["id"] for p in data["programs"]}
    added = []
    skipped = []
    for program in NEW_PROGRAMS:
        if program["id"] in existing_ids:
            skipped.append(program["id"])
            continue
        data["programs"].append(program)
        existing_ids.add(program["id"])
        added.append(program["id"])

    retagged = 0
    for program in data["programs"]:
        before = list(program.get("program", {}).get("tags") or [])
        merge_inferred_tags(program)
        after = list(program.get("program", {}).get("tags") or [])
        if after != before:
            retagged += 1

    data["meta"]["last_built_at"] = VERIFIED
    data["meta"]["scope_note"] = (
        f"共 {len(data['programs'])} 个项目；覆盖商科、计算机、传媒、数据科学、法律、教育、交互设计等；"
        "UK/US/HK/SG；官网公开字段 + 经验性评估，不编造录取概率。"
    )

    DATA_PATH.write_text(
        json.dumps(data, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(f"Added {len(added)} programs (skipped {len(skipped)} duplicates)")
    print(f"Retagged {retagged} existing programs with inferred tags")
    print(f"Total programs: {len(data['programs'])}")
    if skipped:
        print("Skipped:", skipped)


if __name__ == "__main__":
    main()
